// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountDataRequest.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_AccountDataRequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_AccountDataRequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_AccountDataRequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_AccountDataRequest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_AccountDataRequest_2eproto;
namespace protobuf {
class AccountDataRequest;
class AccountDataRequestDefaultTypeInternal;
extern AccountDataRequestDefaultTypeInternal _AccountDataRequest_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::protobuf::AccountDataRequest* Arena::CreateMaybeMessage<::protobuf::AccountDataRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf {

// ===================================================================

class AccountDataRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.AccountDataRequest) */ {
 public:
  inline AccountDataRequest() : AccountDataRequest(nullptr) {};
  virtual ~AccountDataRequest();

  AccountDataRequest(const AccountDataRequest& from);
  AccountDataRequest(AccountDataRequest&& from) noexcept
    : AccountDataRequest() {
    *this = ::std::move(from);
  }

  inline AccountDataRequest& operator=(const AccountDataRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountDataRequest& operator=(AccountDataRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AccountDataRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AccountDataRequest* internal_default_instance() {
    return reinterpret_cast<const AccountDataRequest*>(
               &_AccountDataRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AccountDataRequest& a, AccountDataRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountDataRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountDataRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AccountDataRequest* New() const final {
    return CreateMaybeMessage<AccountDataRequest>(nullptr);
  }

  AccountDataRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AccountDataRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AccountDataRequest& from);
  void MergeFrom(const AccountDataRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountDataRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.AccountDataRequest";
  }
  protected:
  explicit AccountDataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_AccountDataRequest_2eproto);
    return ::descriptor_table_AccountDataRequest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAcctCodeFieldNumber = 2,
    kSubscribeFieldNumber = 1,
  };
  // string acctCode = 2;
  bool has_acctcode() const;
  private:
  bool _internal_has_acctcode() const;
  public:
  void clear_acctcode();
  const std::string& acctcode() const;
  void set_acctcode(const std::string& value);
  void set_acctcode(std::string&& value);
  void set_acctcode(const char* value);
  void set_acctcode(const char* value, size_t size);
  std::string* mutable_acctcode();
  std::string* release_acctcode();
  void set_allocated_acctcode(std::string* acctcode);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_acctcode();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_acctcode(
      std::string* acctcode);
  private:
  const std::string& _internal_acctcode() const;
  void _internal_set_acctcode(const std::string& value);
  std::string* _internal_mutable_acctcode();
  public:

  // bool subscribe = 1;
  bool has_subscribe() const;
  private:
  bool _internal_has_subscribe() const;
  public:
  void clear_subscribe();
  bool subscribe() const;
  void set_subscribe(bool value);
  private:
  bool _internal_subscribe() const;
  void _internal_set_subscribe(bool value);
  public:

  // @@protoc_insertion_point(class_scope:protobuf.AccountDataRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr acctcode_;
  bool subscribe_;
  friend struct ::TableStruct_AccountDataRequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AccountDataRequest

// bool subscribe = 1;
inline bool AccountDataRequest::_internal_has_subscribe() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool AccountDataRequest::has_subscribe() const {
  return _internal_has_subscribe();
}
inline void AccountDataRequest::clear_subscribe() {
  subscribe_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool AccountDataRequest::_internal_subscribe() const {
  return subscribe_;
}
inline bool AccountDataRequest::subscribe() const {
  // @@protoc_insertion_point(field_get:protobuf.AccountDataRequest.subscribe)
  return _internal_subscribe();
}
inline void AccountDataRequest::_internal_set_subscribe(bool value) {
  _has_bits_[0] |= 0x00000002u;
  subscribe_ = value;
}
inline void AccountDataRequest::set_subscribe(bool value) {
  _internal_set_subscribe(value);
  // @@protoc_insertion_point(field_set:protobuf.AccountDataRequest.subscribe)
}

// string acctCode = 2;
inline bool AccountDataRequest::_internal_has_acctcode() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool AccountDataRequest::has_acctcode() const {
  return _internal_has_acctcode();
}
inline void AccountDataRequest::clear_acctcode() {
  acctcode_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& AccountDataRequest::acctcode() const {
  // @@protoc_insertion_point(field_get:protobuf.AccountDataRequest.acctCode)
  return _internal_acctcode();
}
inline void AccountDataRequest::set_acctcode(const std::string& value) {
  _internal_set_acctcode(value);
  // @@protoc_insertion_point(field_set:protobuf.AccountDataRequest.acctCode)
}
inline std::string* AccountDataRequest::mutable_acctcode() {
  // @@protoc_insertion_point(field_mutable:protobuf.AccountDataRequest.acctCode)
  return _internal_mutable_acctcode();
}
inline const std::string& AccountDataRequest::_internal_acctcode() const {
  return acctcode_.Get();
}
inline void AccountDataRequest::_internal_set_acctcode(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  acctcode_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void AccountDataRequest::set_acctcode(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  acctcode_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:protobuf.AccountDataRequest.acctCode)
}
inline void AccountDataRequest::set_acctcode(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  acctcode_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:protobuf.AccountDataRequest.acctCode)
}
inline void AccountDataRequest::set_acctcode(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  acctcode_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:protobuf.AccountDataRequest.acctCode)
}
inline std::string* AccountDataRequest::_internal_mutable_acctcode() {
  _has_bits_[0] |= 0x00000001u;
  return acctcode_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* AccountDataRequest::release_acctcode() {
  // @@protoc_insertion_point(field_release:protobuf.AccountDataRequest.acctCode)
  if (!_internal_has_acctcode()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return acctcode_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AccountDataRequest::set_allocated_acctcode(std::string* acctcode) {
  if (acctcode != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  acctcode_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), acctcode,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:protobuf.AccountDataRequest.acctCode)
}
inline std::string* AccountDataRequest::unsafe_arena_release_acctcode() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobuf.AccountDataRequest.acctCode)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return acctcode_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void AccountDataRequest::unsafe_arena_set_allocated_acctcode(
    std::string* acctcode) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (acctcode != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  acctcode_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      acctcode, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.AccountDataRequest.acctCode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_AccountDataRequest_2eproto
