// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DisplayGroupUpdated.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DisplayGroupUpdated_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DisplayGroupUpdated_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DisplayGroupUpdated_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DisplayGroupUpdated_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DisplayGroupUpdated_2eproto;
namespace protobuf {
class DisplayGroupUpdated;
class DisplayGroupUpdatedDefaultTypeInternal;
extern DisplayGroupUpdatedDefaultTypeInternal _DisplayGroupUpdated_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::protobuf::DisplayGroupUpdated* Arena::CreateMaybeMessage<::protobuf::DisplayGroupUpdated>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf {

// ===================================================================

class DisplayGroupUpdated PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.DisplayGroupUpdated) */ {
 public:
  inline DisplayGroupUpdated() : DisplayGroupUpdated(nullptr) {};
  virtual ~DisplayGroupUpdated();

  DisplayGroupUpdated(const DisplayGroupUpdated& from);
  DisplayGroupUpdated(DisplayGroupUpdated&& from) noexcept
    : DisplayGroupUpdated() {
    *this = ::std::move(from);
  }

  inline DisplayGroupUpdated& operator=(const DisplayGroupUpdated& from) {
    CopyFrom(from);
    return *this;
  }
  inline DisplayGroupUpdated& operator=(DisplayGroupUpdated&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DisplayGroupUpdated& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DisplayGroupUpdated* internal_default_instance() {
    return reinterpret_cast<const DisplayGroupUpdated*>(
               &_DisplayGroupUpdated_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DisplayGroupUpdated& a, DisplayGroupUpdated& b) {
    a.Swap(&b);
  }
  inline void Swap(DisplayGroupUpdated* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DisplayGroupUpdated* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DisplayGroupUpdated* New() const final {
    return CreateMaybeMessage<DisplayGroupUpdated>(nullptr);
  }

  DisplayGroupUpdated* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DisplayGroupUpdated>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DisplayGroupUpdated& from);
  void MergeFrom(const DisplayGroupUpdated& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DisplayGroupUpdated* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.DisplayGroupUpdated";
  }
  protected:
  explicit DisplayGroupUpdated(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_DisplayGroupUpdated_2eproto);
    return ::descriptor_table_DisplayGroupUpdated_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContractInfoFieldNumber = 2,
    kReqIdFieldNumber = 1,
  };
  // string contractInfo = 2;
  bool has_contractinfo() const;
  private:
  bool _internal_has_contractinfo() const;
  public:
  void clear_contractinfo();
  const std::string& contractinfo() const;
  void set_contractinfo(const std::string& value);
  void set_contractinfo(std::string&& value);
  void set_contractinfo(const char* value);
  void set_contractinfo(const char* value, size_t size);
  std::string* mutable_contractinfo();
  std::string* release_contractinfo();
  void set_allocated_contractinfo(std::string* contractinfo);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_contractinfo();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_contractinfo(
      std::string* contractinfo);
  private:
  const std::string& _internal_contractinfo() const;
  void _internal_set_contractinfo(const std::string& value);
  std::string* _internal_mutable_contractinfo();
  public:

  // int32 reqId = 1;
  bool has_reqid() const;
  private:
  bool _internal_has_reqid() const;
  public:
  void clear_reqid();
  ::PROTOBUF_NAMESPACE_ID::int32 reqid() const;
  void set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_reqid() const;
  void _internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protobuf.DisplayGroupUpdated)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr contractinfo_;
  ::PROTOBUF_NAMESPACE_ID::int32 reqid_;
  friend struct ::TableStruct_DisplayGroupUpdated_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DisplayGroupUpdated

// int32 reqId = 1;
inline bool DisplayGroupUpdated::_internal_has_reqid() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool DisplayGroupUpdated::has_reqid() const {
  return _internal_has_reqid();
}
inline void DisplayGroupUpdated::clear_reqid() {
  reqid_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 DisplayGroupUpdated::_internal_reqid() const {
  return reqid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 DisplayGroupUpdated::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.DisplayGroupUpdated.reqId)
  return _internal_reqid();
}
inline void DisplayGroupUpdated::_internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  reqid_ = value;
}
inline void DisplayGroupUpdated::set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_reqid(value);
  // @@protoc_insertion_point(field_set:protobuf.DisplayGroupUpdated.reqId)
}

// string contractInfo = 2;
inline bool DisplayGroupUpdated::_internal_has_contractinfo() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool DisplayGroupUpdated::has_contractinfo() const {
  return _internal_has_contractinfo();
}
inline void DisplayGroupUpdated::clear_contractinfo() {
  contractinfo_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& DisplayGroupUpdated::contractinfo() const {
  // @@protoc_insertion_point(field_get:protobuf.DisplayGroupUpdated.contractInfo)
  return _internal_contractinfo();
}
inline void DisplayGroupUpdated::set_contractinfo(const std::string& value) {
  _internal_set_contractinfo(value);
  // @@protoc_insertion_point(field_set:protobuf.DisplayGroupUpdated.contractInfo)
}
inline std::string* DisplayGroupUpdated::mutable_contractinfo() {
  // @@protoc_insertion_point(field_mutable:protobuf.DisplayGroupUpdated.contractInfo)
  return _internal_mutable_contractinfo();
}
inline const std::string& DisplayGroupUpdated::_internal_contractinfo() const {
  return contractinfo_.Get();
}
inline void DisplayGroupUpdated::_internal_set_contractinfo(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  contractinfo_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void DisplayGroupUpdated::set_contractinfo(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  contractinfo_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:protobuf.DisplayGroupUpdated.contractInfo)
}
inline void DisplayGroupUpdated::set_contractinfo(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  contractinfo_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:protobuf.DisplayGroupUpdated.contractInfo)
}
inline void DisplayGroupUpdated::set_contractinfo(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  contractinfo_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:protobuf.DisplayGroupUpdated.contractInfo)
}
inline std::string* DisplayGroupUpdated::_internal_mutable_contractinfo() {
  _has_bits_[0] |= 0x00000001u;
  return contractinfo_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* DisplayGroupUpdated::release_contractinfo() {
  // @@protoc_insertion_point(field_release:protobuf.DisplayGroupUpdated.contractInfo)
  if (!_internal_has_contractinfo()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return contractinfo_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void DisplayGroupUpdated::set_allocated_contractinfo(std::string* contractinfo) {
  if (contractinfo != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  contractinfo_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), contractinfo,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:protobuf.DisplayGroupUpdated.contractInfo)
}
inline std::string* DisplayGroupUpdated::unsafe_arena_release_contractinfo() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobuf.DisplayGroupUpdated.contractInfo)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return contractinfo_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void DisplayGroupUpdated::unsafe_arena_set_allocated_contractinfo(
    std::string* contractinfo) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (contractinfo != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  contractinfo_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      contractinfo, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.DisplayGroupUpdated.contractInfo)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DisplayGroupUpdated_2eproto
