// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeadTimestampRequest.proto

#include "HeadTimestampRequest.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_Contract_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_Contract_Contract_2eproto;
namespace protobuf {
class HeadTimestampRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<HeadTimestampRequest> _instance;
} _HeadTimestampRequest_default_instance_;
}  // namespace protobuf
static void InitDefaultsscc_info_HeadTimestampRequest_HeadTimestampRequest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protobuf::_HeadTimestampRequest_default_instance_;
    new (ptr) ::protobuf::HeadTimestampRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protobuf::HeadTimestampRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_HeadTimestampRequest_HeadTimestampRequest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_HeadTimestampRequest_HeadTimestampRequest_2eproto}, {
      &scc_info_Contract_Contract_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_HeadTimestampRequest_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_HeadTimestampRequest_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_HeadTimestampRequest_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_HeadTimestampRequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::protobuf::HeadTimestampRequest, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HeadTimestampRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protobuf::HeadTimestampRequest, reqid_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HeadTimestampRequest, contract_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HeadTimestampRequest, userth_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HeadTimestampRequest, whattoshow_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HeadTimestampRequest, formatdate_),
  2,
  1,
  3,
  0,
  4,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, sizeof(::protobuf::HeadTimestampRequest)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_HeadTimestampRequest_default_instance_),
};

const char descriptor_table_protodef_HeadTimestampRequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032HeadTimestampRequest.proto\022\010protobuf\032\016"
  "Contract.proto\"\334\001\n\024HeadTimestampRequest\022"
  "\022\n\005reqId\030\001 \001(\005H\000\210\001\001\022)\n\010contract\030\002 \001(\0132\022."
  "protobuf.ContractH\001\210\001\001\022\023\n\006useRTH\030\003 \001(\010H\002"
  "\210\001\001\022\027\n\nwhatToShow\030\004 \001(\tH\003\210\001\001\022\027\n\nformatDa"
  "te\030\005 \001(\005H\004\210\001\001B\010\n\006_reqIdB\013\n\t_contractB\t\n\007"
  "_useRTHB\r\n\013_whatToShowB\r\n\013_formatDateBD\n"
  "\026com.ib.client.protobufB\031HeadTimestampRe"
  "questProto\252\002\016IBApi.protobufb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_HeadTimestampRequest_2eproto_deps[1] = {
  &::descriptor_table_Contract_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_HeadTimestampRequest_2eproto_sccs[1] = {
  &scc_info_HeadTimestampRequest_HeadTimestampRequest_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_HeadTimestampRequest_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HeadTimestampRequest_2eproto = {
  false, false, descriptor_table_protodef_HeadTimestampRequest_2eproto, "HeadTimestampRequest.proto", 355,
  &descriptor_table_HeadTimestampRequest_2eproto_once, descriptor_table_HeadTimestampRequest_2eproto_sccs, descriptor_table_HeadTimestampRequest_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_HeadTimestampRequest_2eproto::offsets,
  file_level_metadata_HeadTimestampRequest_2eproto, 1, file_level_enum_descriptors_HeadTimestampRequest_2eproto, file_level_service_descriptors_HeadTimestampRequest_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_HeadTimestampRequest_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_HeadTimestampRequest_2eproto)), true);
namespace protobuf {

// ===================================================================

void HeadTimestampRequest::InitAsDefaultInstance() {
  ::protobuf::_HeadTimestampRequest_default_instance_._instance.get_mutable()->contract_ = const_cast< ::protobuf::Contract*>(
      ::protobuf::Contract::internal_default_instance());
}
class HeadTimestampRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<HeadTimestampRequest>()._has_bits_);
  static void set_has_reqid(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::protobuf::Contract& contract(const HeadTimestampRequest* msg);
  static void set_has_contract(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_userth(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_whattoshow(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_formatdate(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
};

const ::protobuf::Contract&
HeadTimestampRequest::_Internal::contract(const HeadTimestampRequest* msg) {
  return *msg->contract_;
}
void HeadTimestampRequest::clear_contract() {
  if (GetArena() == nullptr && contract_ != nullptr) {
    delete contract_;
  }
  contract_ = nullptr;
  _has_bits_[0] &= ~0x00000002u;
}
HeadTimestampRequest::HeadTimestampRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.HeadTimestampRequest)
}
HeadTimestampRequest::HeadTimestampRequest(const HeadTimestampRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  whattoshow_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_whattoshow()) {
    whattoshow_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_whattoshow(),
      GetArena());
  }
  if (from._internal_has_contract()) {
    contract_ = new ::protobuf::Contract(*from.contract_);
  } else {
    contract_ = nullptr;
  }
  ::memcpy(&reqid_, &from.reqid_,
    static_cast<size_t>(reinterpret_cast<char*>(&formatdate_) -
    reinterpret_cast<char*>(&reqid_)) + sizeof(formatdate_));
  // @@protoc_insertion_point(copy_constructor:protobuf.HeadTimestampRequest)
}

void HeadTimestampRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_HeadTimestampRequest_HeadTimestampRequest_2eproto.base);
  whattoshow_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&contract_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&formatdate_) -
      reinterpret_cast<char*>(&contract_)) + sizeof(formatdate_));
}

HeadTimestampRequest::~HeadTimestampRequest() {
  // @@protoc_insertion_point(destructor:protobuf.HeadTimestampRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void HeadTimestampRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  whattoshow_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete contract_;
}

void HeadTimestampRequest::ArenaDtor(void* object) {
  HeadTimestampRequest* _this = reinterpret_cast< HeadTimestampRequest* >(object);
  (void)_this;
}
void HeadTimestampRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void HeadTimestampRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const HeadTimestampRequest& HeadTimestampRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_HeadTimestampRequest_HeadTimestampRequest_2eproto.base);
  return *internal_default_instance();
}


void HeadTimestampRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.HeadTimestampRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      whattoshow_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      if (GetArena() == nullptr && contract_ != nullptr) {
        delete contract_;
      }
      contract_ = nullptr;
    }
  }
  if (cached_has_bits & 0x0000001cu) {
    ::memset(&reqid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&formatdate_) -
        reinterpret_cast<char*>(&reqid_)) + sizeof(formatdate_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HeadTimestampRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 reqId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_reqid(&has_bits);
          reqid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .protobuf.Contract contract = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_contract(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool useRTH = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_userth(&has_bits);
          userth_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string whatToShow = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_whattoshow();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.HeadTimestampRequest.whatToShow"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 formatDate = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_formatdate(&has_bits);
          formatdate_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* HeadTimestampRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.HeadTimestampRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 reqId = 1;
  if (_internal_has_reqid()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_reqid(), target);
  }

  // .protobuf.Contract contract = 2;
  if (_internal_has_contract()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::contract(this), target, stream);
  }

  // bool useRTH = 3;
  if (_internal_has_userth()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_userth(), target);
  }

  // string whatToShow = 4;
  if (_internal_has_whattoshow()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_whattoshow().data(), static_cast<int>(this->_internal_whattoshow().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.HeadTimestampRequest.whatToShow");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_whattoshow(), target);
  }

  // int32 formatDate = 5;
  if (_internal_has_formatdate()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_formatdate(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.HeadTimestampRequest)
  return target;
}

size_t HeadTimestampRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.HeadTimestampRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // string whatToShow = 4;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_whattoshow());
    }

    // .protobuf.Contract contract = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *contract_);
    }

    // int32 reqId = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_reqid());
    }

    // bool useRTH = 3;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

    // int32 formatDate = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_formatdate());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void HeadTimestampRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protobuf.HeadTimestampRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const HeadTimestampRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<HeadTimestampRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protobuf.HeadTimestampRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protobuf.HeadTimestampRequest)
    MergeFrom(*source);
  }
}

void HeadTimestampRequest::MergeFrom(const HeadTimestampRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.HeadTimestampRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_whattoshow(from._internal_whattoshow());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_contract()->::protobuf::Contract::MergeFrom(from._internal_contract());
    }
    if (cached_has_bits & 0x00000004u) {
      reqid_ = from.reqid_;
    }
    if (cached_has_bits & 0x00000008u) {
      userth_ = from.userth_;
    }
    if (cached_has_bits & 0x00000010u) {
      formatdate_ = from.formatdate_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void HeadTimestampRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protobuf.HeadTimestampRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HeadTimestampRequest::CopyFrom(const HeadTimestampRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.HeadTimestampRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HeadTimestampRequest::IsInitialized() const {
  return true;
}

void HeadTimestampRequest::InternalSwap(HeadTimestampRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  whattoshow_.Swap(&other->whattoshow_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HeadTimestampRequest, formatdate_)
      + sizeof(HeadTimestampRequest::formatdate_)
      - PROTOBUF_FIELD_OFFSET(HeadTimestampRequest, contract_)>(
          reinterpret_cast<char*>(&contract_),
          reinterpret_cast<char*>(&other->contract_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HeadTimestampRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::HeadTimestampRequest* Arena::CreateMaybeMessage< ::protobuf::HeadTimestampRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::HeadTimestampRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
