// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HistoricalDataUpdate.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_HistoricalDataUpdate_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_HistoricalDataUpdate_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "HistoricalDataBar.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_HistoricalDataUpdate_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_HistoricalDataUpdate_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HistoricalDataUpdate_2eproto;
namespace protobuf {
class HistoricalDataUpdate;
class HistoricalDataUpdateDefaultTypeInternal;
extern HistoricalDataUpdateDefaultTypeInternal _HistoricalDataUpdate_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::protobuf::HistoricalDataUpdate* Arena::CreateMaybeMessage<::protobuf::HistoricalDataUpdate>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf {

// ===================================================================

class HistoricalDataUpdate PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.HistoricalDataUpdate) */ {
 public:
  inline HistoricalDataUpdate() : HistoricalDataUpdate(nullptr) {};
  virtual ~HistoricalDataUpdate();

  HistoricalDataUpdate(const HistoricalDataUpdate& from);
  HistoricalDataUpdate(HistoricalDataUpdate&& from) noexcept
    : HistoricalDataUpdate() {
    *this = ::std::move(from);
  }

  inline HistoricalDataUpdate& operator=(const HistoricalDataUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline HistoricalDataUpdate& operator=(HistoricalDataUpdate&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const HistoricalDataUpdate& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HistoricalDataUpdate* internal_default_instance() {
    return reinterpret_cast<const HistoricalDataUpdate*>(
               &_HistoricalDataUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HistoricalDataUpdate& a, HistoricalDataUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(HistoricalDataUpdate* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HistoricalDataUpdate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline HistoricalDataUpdate* New() const final {
    return CreateMaybeMessage<HistoricalDataUpdate>(nullptr);
  }

  HistoricalDataUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<HistoricalDataUpdate>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const HistoricalDataUpdate& from);
  void MergeFrom(const HistoricalDataUpdate& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HistoricalDataUpdate* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.HistoricalDataUpdate";
  }
  protected:
  explicit HistoricalDataUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_HistoricalDataUpdate_2eproto);
    return ::descriptor_table_HistoricalDataUpdate_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHistoricalDataBarFieldNumber = 2,
    kReqIdFieldNumber = 1,
  };
  // .protobuf.HistoricalDataBar historicalDataBar = 2;
  bool has_historicaldatabar() const;
  private:
  bool _internal_has_historicaldatabar() const;
  public:
  void clear_historicaldatabar();
  const ::protobuf::HistoricalDataBar& historicaldatabar() const;
  ::protobuf::HistoricalDataBar* release_historicaldatabar();
  ::protobuf::HistoricalDataBar* mutable_historicaldatabar();
  void set_allocated_historicaldatabar(::protobuf::HistoricalDataBar* historicaldatabar);
  private:
  const ::protobuf::HistoricalDataBar& _internal_historicaldatabar() const;
  ::protobuf::HistoricalDataBar* _internal_mutable_historicaldatabar();
  public:
  void unsafe_arena_set_allocated_historicaldatabar(
      ::protobuf::HistoricalDataBar* historicaldatabar);
  ::protobuf::HistoricalDataBar* unsafe_arena_release_historicaldatabar();

  // int32 reqId = 1;
  bool has_reqid() const;
  private:
  bool _internal_has_reqid() const;
  public:
  void clear_reqid();
  ::PROTOBUF_NAMESPACE_ID::int32 reqid() const;
  void set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_reqid() const;
  void _internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protobuf.HistoricalDataUpdate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::protobuf::HistoricalDataBar* historicaldatabar_;
  ::PROTOBUF_NAMESPACE_ID::int32 reqid_;
  friend struct ::TableStruct_HistoricalDataUpdate_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HistoricalDataUpdate

// int32 reqId = 1;
inline bool HistoricalDataUpdate::_internal_has_reqid() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool HistoricalDataUpdate::has_reqid() const {
  return _internal_has_reqid();
}
inline void HistoricalDataUpdate::clear_reqid() {
  reqid_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 HistoricalDataUpdate::_internal_reqid() const {
  return reqid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 HistoricalDataUpdate::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalDataUpdate.reqId)
  return _internal_reqid();
}
inline void HistoricalDataUpdate::_internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  reqid_ = value;
}
inline void HistoricalDataUpdate::set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_reqid(value);
  // @@protoc_insertion_point(field_set:protobuf.HistoricalDataUpdate.reqId)
}

// .protobuf.HistoricalDataBar historicalDataBar = 2;
inline bool HistoricalDataUpdate::_internal_has_historicaldatabar() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || historicaldatabar_ != nullptr);
  return value;
}
inline bool HistoricalDataUpdate::has_historicaldatabar() const {
  return _internal_has_historicaldatabar();
}
inline const ::protobuf::HistoricalDataBar& HistoricalDataUpdate::_internal_historicaldatabar() const {
  const ::protobuf::HistoricalDataBar* p = historicaldatabar_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protobuf::HistoricalDataBar*>(
      &::protobuf::_HistoricalDataBar_default_instance_);
}
inline const ::protobuf::HistoricalDataBar& HistoricalDataUpdate::historicaldatabar() const {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalDataUpdate.historicalDataBar)
  return _internal_historicaldatabar();
}
inline void HistoricalDataUpdate::unsafe_arena_set_allocated_historicaldatabar(
    ::protobuf::HistoricalDataBar* historicaldatabar) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(historicaldatabar_);
  }
  historicaldatabar_ = historicaldatabar;
  if (historicaldatabar) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.HistoricalDataUpdate.historicalDataBar)
}
inline ::protobuf::HistoricalDataBar* HistoricalDataUpdate::release_historicaldatabar() {
  auto temp = unsafe_arena_release_historicaldatabar();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::protobuf::HistoricalDataBar* HistoricalDataUpdate::unsafe_arena_release_historicaldatabar() {
  // @@protoc_insertion_point(field_release:protobuf.HistoricalDataUpdate.historicalDataBar)
  _has_bits_[0] &= ~0x00000001u;
  ::protobuf::HistoricalDataBar* temp = historicaldatabar_;
  historicaldatabar_ = nullptr;
  return temp;
}
inline ::protobuf::HistoricalDataBar* HistoricalDataUpdate::_internal_mutable_historicaldatabar() {
  _has_bits_[0] |= 0x00000001u;
  if (historicaldatabar_ == nullptr) {
    auto* p = CreateMaybeMessage<::protobuf::HistoricalDataBar>(GetArena());
    historicaldatabar_ = p;
  }
  return historicaldatabar_;
}
inline ::protobuf::HistoricalDataBar* HistoricalDataUpdate::mutable_historicaldatabar() {
  // @@protoc_insertion_point(field_mutable:protobuf.HistoricalDataUpdate.historicalDataBar)
  return _internal_mutable_historicaldatabar();
}
inline void HistoricalDataUpdate::set_allocated_historicaldatabar(::protobuf::HistoricalDataBar* historicaldatabar) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(historicaldatabar_);
  }
  if (historicaldatabar) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(historicaldatabar)->GetArena();
    if (message_arena != submessage_arena) {
      historicaldatabar = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, historicaldatabar, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  historicaldatabar_ = historicaldatabar;
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistoricalDataUpdate.historicalDataBar)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_HistoricalDataUpdate_2eproto
