// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HistoricalData.proto

#include "HistoricalData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_HistoricalDataBar_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_HistoricalDataBar_HistoricalDataBar_2eproto;
namespace protobuf {
class HistoricalDataDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<HistoricalData> _instance;
} _HistoricalData_default_instance_;
}  // namespace protobuf
static void InitDefaultsscc_info_HistoricalData_HistoricalData_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protobuf::_HistoricalData_default_instance_;
    new (ptr) ::protobuf::HistoricalData();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protobuf::HistoricalData::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_HistoricalData_HistoricalData_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_HistoricalData_HistoricalData_2eproto}, {
      &scc_info_HistoricalDataBar_HistoricalDataBar_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_HistoricalData_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_HistoricalData_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_HistoricalData_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_HistoricalData_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalData, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalData, reqid_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalData, historicaldatabars_),
  0,
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::protobuf::HistoricalData)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_HistoricalData_default_instance_),
};

const char descriptor_table_protodef_HistoricalData_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024HistoricalData.proto\022\010protobuf\032\027Histor"
  "icalDataBar.proto\"g\n\016HistoricalData\022\022\n\005r"
  "eqId\030\001 \001(\005H\000\210\001\001\0227\n\022historicalDataBars\030\002 "
  "\003(\0132\033.protobuf.HistoricalDataBarB\010\n\006_req"
  "IdB>\n\026com.ib.client.protobufB\023Historical"
  "DataProto\252\002\016IBApi.protobufb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_HistoricalData_2eproto_deps[1] = {
  &::descriptor_table_HistoricalDataBar_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_HistoricalData_2eproto_sccs[1] = {
  &scc_info_HistoricalData_HistoricalData_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_HistoricalData_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HistoricalData_2eproto = {
  false, false, descriptor_table_protodef_HistoricalData_2eproto, "HistoricalData.proto", 234,
  &descriptor_table_HistoricalData_2eproto_once, descriptor_table_HistoricalData_2eproto_sccs, descriptor_table_HistoricalData_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_HistoricalData_2eproto::offsets,
  file_level_metadata_HistoricalData_2eproto, 1, file_level_enum_descriptors_HistoricalData_2eproto, file_level_service_descriptors_HistoricalData_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_HistoricalData_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_HistoricalData_2eproto)), true);
namespace protobuf {

// ===================================================================

void HistoricalData::InitAsDefaultInstance() {
}
class HistoricalData::_Internal {
 public:
  using HasBits = decltype(std::declval<HistoricalData>()._has_bits_);
  static void set_has_reqid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

void HistoricalData::clear_historicaldatabars() {
  historicaldatabars_.Clear();
}
HistoricalData::HistoricalData(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  historicaldatabars_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.HistoricalData)
}
HistoricalData::HistoricalData(const HistoricalData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      historicaldatabars_(from.historicaldatabars_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  reqid_ = from.reqid_;
  // @@protoc_insertion_point(copy_constructor:protobuf.HistoricalData)
}

void HistoricalData::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_HistoricalData_HistoricalData_2eproto.base);
  reqid_ = 0;
}

HistoricalData::~HistoricalData() {
  // @@protoc_insertion_point(destructor:protobuf.HistoricalData)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void HistoricalData::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void HistoricalData::ArenaDtor(void* object) {
  HistoricalData* _this = reinterpret_cast< HistoricalData* >(object);
  (void)_this;
}
void HistoricalData::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void HistoricalData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const HistoricalData& HistoricalData::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_HistoricalData_HistoricalData_2eproto.base);
  return *internal_default_instance();
}


void HistoricalData::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.HistoricalData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  historicaldatabars_.Clear();
  reqid_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HistoricalData::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 reqId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_reqid(&has_bits);
          reqid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .protobuf.HistoricalDataBar historicalDataBars = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_historicaldatabars(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* HistoricalData::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.HistoricalData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 reqId = 1;
  if (_internal_has_reqid()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_reqid(), target);
  }

  // repeated .protobuf.HistoricalDataBar historicalDataBars = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_historicaldatabars_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_historicaldatabars(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.HistoricalData)
  return target;
}

size_t HistoricalData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.HistoricalData)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .protobuf.HistoricalDataBar historicalDataBars = 2;
  total_size += 1UL * this->_internal_historicaldatabars_size();
  for (const auto& msg : this->historicaldatabars_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 reqId = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_reqid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void HistoricalData::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protobuf.HistoricalData)
  GOOGLE_DCHECK_NE(&from, this);
  const HistoricalData* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<HistoricalData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protobuf.HistoricalData)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protobuf.HistoricalData)
    MergeFrom(*source);
  }
}

void HistoricalData::MergeFrom(const HistoricalData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.HistoricalData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  historicaldatabars_.MergeFrom(from.historicaldatabars_);
  if (from._internal_has_reqid()) {
    _internal_set_reqid(from._internal_reqid());
  }
}

void HistoricalData::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protobuf.HistoricalData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HistoricalData::CopyFrom(const HistoricalData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.HistoricalData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HistoricalData::IsInitialized() const {
  return true;
}

void HistoricalData::InternalSwap(HistoricalData* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  historicaldatabars_.InternalSwap(&other->historicaldatabars_);
  swap(reqid_, other->reqid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HistoricalData::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::HistoricalData* Arena::CreateMaybeMessage< ::protobuf::HistoricalData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::HistoricalData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
