// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HistoricalDataEnd.proto

#include "HistoricalDataEnd.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace protobuf {
class HistoricalDataEndDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<HistoricalDataEnd> _instance;
} _HistoricalDataEnd_default_instance_;
}  // namespace protobuf
static void InitDefaultsscc_info_HistoricalDataEnd_HistoricalDataEnd_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protobuf::_HistoricalDataEnd_default_instance_;
    new (ptr) ::protobuf::HistoricalDataEnd();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protobuf::HistoricalDataEnd::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_HistoricalDataEnd_HistoricalDataEnd_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_HistoricalDataEnd_HistoricalDataEnd_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_HistoricalDataEnd_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_HistoricalDataEnd_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_HistoricalDataEnd_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_HistoricalDataEnd_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalDataEnd, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalDataEnd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalDataEnd, reqid_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalDataEnd, startdatestr_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalDataEnd, enddatestr_),
  2,
  0,
  1,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::protobuf::HistoricalDataEnd)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_HistoricalDataEnd_default_instance_),
};

const char descriptor_table_protodef_HistoricalDataEnd_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027HistoricalDataEnd.proto\022\010protobuf\"\205\001\n\021"
  "HistoricalDataEnd\022\022\n\005reqId\030\001 \001(\005H\000\210\001\001\022\031\n"
  "\014startDateStr\030\002 \001(\tH\001\210\001\001\022\027\n\nendDateStr\030\003"
  " \001(\tH\002\210\001\001B\010\n\006_reqIdB\017\n\r_startDateStrB\r\n\013"
  "_endDateStrBA\n\026com.ib.client.protobufB\026H"
  "istoricalDataEndProto\252\002\016IBApi.protobufb\006"
  "proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_HistoricalDataEnd_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_HistoricalDataEnd_2eproto_sccs[1] = {
  &scc_info_HistoricalDataEnd_HistoricalDataEnd_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_HistoricalDataEnd_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HistoricalDataEnd_2eproto = {
  false, false, descriptor_table_protodef_HistoricalDataEnd_2eproto, "HistoricalDataEnd.proto", 246,
  &descriptor_table_HistoricalDataEnd_2eproto_once, descriptor_table_HistoricalDataEnd_2eproto_sccs, descriptor_table_HistoricalDataEnd_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_HistoricalDataEnd_2eproto::offsets,
  file_level_metadata_HistoricalDataEnd_2eproto, 1, file_level_enum_descriptors_HistoricalDataEnd_2eproto, file_level_service_descriptors_HistoricalDataEnd_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_HistoricalDataEnd_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_HistoricalDataEnd_2eproto)), true);
namespace protobuf {

// ===================================================================

void HistoricalDataEnd::InitAsDefaultInstance() {
}
class HistoricalDataEnd::_Internal {
 public:
  using HasBits = decltype(std::declval<HistoricalDataEnd>()._has_bits_);
  static void set_has_reqid(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_startdatestr(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_enddatestr(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

HistoricalDataEnd::HistoricalDataEnd(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.HistoricalDataEnd)
}
HistoricalDataEnd::HistoricalDataEnd(const HistoricalDataEnd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  startdatestr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_startdatestr()) {
    startdatestr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_startdatestr(),
      GetArena());
  }
  enddatestr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_enddatestr()) {
    enddatestr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_enddatestr(),
      GetArena());
  }
  reqid_ = from.reqid_;
  // @@protoc_insertion_point(copy_constructor:protobuf.HistoricalDataEnd)
}

void HistoricalDataEnd::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_HistoricalDataEnd_HistoricalDataEnd_2eproto.base);
  startdatestr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  enddatestr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  reqid_ = 0;
}

HistoricalDataEnd::~HistoricalDataEnd() {
  // @@protoc_insertion_point(destructor:protobuf.HistoricalDataEnd)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void HistoricalDataEnd::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  startdatestr_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  enddatestr_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void HistoricalDataEnd::ArenaDtor(void* object) {
  HistoricalDataEnd* _this = reinterpret_cast< HistoricalDataEnd* >(object);
  (void)_this;
}
void HistoricalDataEnd::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void HistoricalDataEnd::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const HistoricalDataEnd& HistoricalDataEnd::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_HistoricalDataEnd_HistoricalDataEnd_2eproto.base);
  return *internal_default_instance();
}


void HistoricalDataEnd::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.HistoricalDataEnd)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      startdatestr_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      enddatestr_.ClearNonDefaultToEmpty();
    }
  }
  reqid_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HistoricalDataEnd::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 reqId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_reqid(&has_bits);
          reqid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string startDateStr = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_startdatestr();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.HistoricalDataEnd.startDateStr"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string endDateStr = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_enddatestr();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.HistoricalDataEnd.endDateStr"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* HistoricalDataEnd::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.HistoricalDataEnd)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 reqId = 1;
  if (_internal_has_reqid()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_reqid(), target);
  }

  // string startDateStr = 2;
  if (_internal_has_startdatestr()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_startdatestr().data(), static_cast<int>(this->_internal_startdatestr().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.HistoricalDataEnd.startDateStr");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_startdatestr(), target);
  }

  // string endDateStr = 3;
  if (_internal_has_enddatestr()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_enddatestr().data(), static_cast<int>(this->_internal_enddatestr().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.HistoricalDataEnd.endDateStr");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_enddatestr(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.HistoricalDataEnd)
  return target;
}

size_t HistoricalDataEnd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.HistoricalDataEnd)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // string startDateStr = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_startdatestr());
    }

    // string endDateStr = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_enddatestr());
    }

    // int32 reqId = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_reqid());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void HistoricalDataEnd::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protobuf.HistoricalDataEnd)
  GOOGLE_DCHECK_NE(&from, this);
  const HistoricalDataEnd* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<HistoricalDataEnd>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protobuf.HistoricalDataEnd)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protobuf.HistoricalDataEnd)
    MergeFrom(*source);
  }
}

void HistoricalDataEnd::MergeFrom(const HistoricalDataEnd& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.HistoricalDataEnd)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_startdatestr(from._internal_startdatestr());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_enddatestr(from._internal_enddatestr());
    }
    if (cached_has_bits & 0x00000004u) {
      reqid_ = from.reqid_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void HistoricalDataEnd::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protobuf.HistoricalDataEnd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HistoricalDataEnd::CopyFrom(const HistoricalDataEnd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.HistoricalDataEnd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HistoricalDataEnd::IsInitialized() const {
  return true;
}

void HistoricalDataEnd::InternalSwap(HistoricalDataEnd* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  startdatestr_.Swap(&other->startdatestr_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  enddatestr_.Swap(&other->enddatestr_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(reqid_, other->reqid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HistoricalDataEnd::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::HistoricalDataEnd* Arena::CreateMaybeMessage< ::protobuf::HistoricalDataEnd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::HistoricalDataEnd >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
