// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HistoricalSchedule.proto

#include "HistoricalSchedule.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_HistoricalSession_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_HistoricalSession_HistoricalSession_2eproto;
namespace protobuf {
class HistoricalScheduleDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<HistoricalSchedule> _instance;
} _HistoricalSchedule_default_instance_;
}  // namespace protobuf
static void InitDefaultsscc_info_HistoricalSchedule_HistoricalSchedule_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protobuf::_HistoricalSchedule_default_instance_;
    new (ptr) ::protobuf::HistoricalSchedule();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protobuf::HistoricalSchedule::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_HistoricalSchedule_HistoricalSchedule_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_HistoricalSchedule_HistoricalSchedule_2eproto}, {
      &scc_info_HistoricalSession_HistoricalSession_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_HistoricalSchedule_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_HistoricalSchedule_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_HistoricalSchedule_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_HistoricalSchedule_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalSchedule, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalSchedule, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalSchedule, reqid_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalSchedule, startdatetime_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalSchedule, enddatetime_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalSchedule, timezone_),
  PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalSchedule, historicalsessions_),
  3,
  0,
  1,
  2,
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, sizeof(::protobuf::HistoricalSchedule)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_HistoricalSchedule_default_instance_),
};

const char descriptor_table_protodef_HistoricalSchedule_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030HistoricalSchedule.proto\022\010protobuf\032\027Hi"
  "storicalSession.proto\"\347\001\n\022HistoricalSche"
  "dule\022\022\n\005reqId\030\001 \001(\005H\000\210\001\001\022\032\n\rstartDateTim"
  "e\030\002 \001(\tH\001\210\001\001\022\030\n\013endDateTime\030\003 \001(\tH\002\210\001\001\022\025"
  "\n\010timeZone\030\004 \001(\tH\003\210\001\001\0227\n\022historicalSessi"
  "ons\030\005 \003(\0132\033.protobuf.HistoricalSessionB\010"
  "\n\006_reqIdB\020\n\016_startDateTimeB\016\n\014_endDateTi"
  "meB\013\n\t_timeZoneBB\n\026com.ib.client.protobu"
  "fB\027HistoricalScheduleProto\252\002\016IBApi.proto"
  "bufb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_HistoricalSchedule_2eproto_deps[1] = {
  &::descriptor_table_HistoricalSession_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_HistoricalSchedule_2eproto_sccs[1] = {
  &scc_info_HistoricalSchedule_HistoricalSchedule_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_HistoricalSchedule_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HistoricalSchedule_2eproto = {
  false, false, descriptor_table_protodef_HistoricalSchedule_2eproto, "HistoricalSchedule.proto", 371,
  &descriptor_table_HistoricalSchedule_2eproto_once, descriptor_table_HistoricalSchedule_2eproto_sccs, descriptor_table_HistoricalSchedule_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_HistoricalSchedule_2eproto::offsets,
  file_level_metadata_HistoricalSchedule_2eproto, 1, file_level_enum_descriptors_HistoricalSchedule_2eproto, file_level_service_descriptors_HistoricalSchedule_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_HistoricalSchedule_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_HistoricalSchedule_2eproto)), true);
namespace protobuf {

// ===================================================================

void HistoricalSchedule::InitAsDefaultInstance() {
}
class HistoricalSchedule::_Internal {
 public:
  using HasBits = decltype(std::declval<HistoricalSchedule>()._has_bits_);
  static void set_has_reqid(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_startdatetime(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_enddatetime(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_timezone(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

void HistoricalSchedule::clear_historicalsessions() {
  historicalsessions_.Clear();
}
HistoricalSchedule::HistoricalSchedule(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  historicalsessions_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.HistoricalSchedule)
}
HistoricalSchedule::HistoricalSchedule(const HistoricalSchedule& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      historicalsessions_(from.historicalsessions_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  startdatetime_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_startdatetime()) {
    startdatetime_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_startdatetime(),
      GetArena());
  }
  enddatetime_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_enddatetime()) {
    enddatetime_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_enddatetime(),
      GetArena());
  }
  timezone_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_timezone()) {
    timezone_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_timezone(),
      GetArena());
  }
  reqid_ = from.reqid_;
  // @@protoc_insertion_point(copy_constructor:protobuf.HistoricalSchedule)
}

void HistoricalSchedule::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_HistoricalSchedule_HistoricalSchedule_2eproto.base);
  startdatetime_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  enddatetime_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  timezone_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  reqid_ = 0;
}

HistoricalSchedule::~HistoricalSchedule() {
  // @@protoc_insertion_point(destructor:protobuf.HistoricalSchedule)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void HistoricalSchedule::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  startdatetime_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  enddatetime_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  timezone_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void HistoricalSchedule::ArenaDtor(void* object) {
  HistoricalSchedule* _this = reinterpret_cast< HistoricalSchedule* >(object);
  (void)_this;
}
void HistoricalSchedule::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void HistoricalSchedule::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const HistoricalSchedule& HistoricalSchedule::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_HistoricalSchedule_HistoricalSchedule_2eproto.base);
  return *internal_default_instance();
}


void HistoricalSchedule::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.HistoricalSchedule)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  historicalsessions_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      startdatetime_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      enddatetime_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      timezone_.ClearNonDefaultToEmpty();
    }
  }
  reqid_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HistoricalSchedule::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 reqId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_reqid(&has_bits);
          reqid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string startDateTime = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_startdatetime();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.HistoricalSchedule.startDateTime"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string endDateTime = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_enddatetime();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.HistoricalSchedule.endDateTime"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string timeZone = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_timezone();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.HistoricalSchedule.timeZone"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .protobuf.HistoricalSession historicalSessions = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_historicalsessions(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* HistoricalSchedule::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.HistoricalSchedule)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 reqId = 1;
  if (_internal_has_reqid()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_reqid(), target);
  }

  // string startDateTime = 2;
  if (_internal_has_startdatetime()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_startdatetime().data(), static_cast<int>(this->_internal_startdatetime().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.HistoricalSchedule.startDateTime");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_startdatetime(), target);
  }

  // string endDateTime = 3;
  if (_internal_has_enddatetime()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_enddatetime().data(), static_cast<int>(this->_internal_enddatetime().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.HistoricalSchedule.endDateTime");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_enddatetime(), target);
  }

  // string timeZone = 4;
  if (_internal_has_timezone()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_timezone().data(), static_cast<int>(this->_internal_timezone().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.HistoricalSchedule.timeZone");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_timezone(), target);
  }

  // repeated .protobuf.HistoricalSession historicalSessions = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_historicalsessions_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, this->_internal_historicalsessions(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.HistoricalSchedule)
  return target;
}

size_t HistoricalSchedule::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.HistoricalSchedule)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .protobuf.HistoricalSession historicalSessions = 5;
  total_size += 1UL * this->_internal_historicalsessions_size();
  for (const auto& msg : this->historicalsessions_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // string startDateTime = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_startdatetime());
    }

    // string endDateTime = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_enddatetime());
    }

    // string timeZone = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_timezone());
    }

    // int32 reqId = 1;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_reqid());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void HistoricalSchedule::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protobuf.HistoricalSchedule)
  GOOGLE_DCHECK_NE(&from, this);
  const HistoricalSchedule* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<HistoricalSchedule>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protobuf.HistoricalSchedule)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protobuf.HistoricalSchedule)
    MergeFrom(*source);
  }
}

void HistoricalSchedule::MergeFrom(const HistoricalSchedule& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.HistoricalSchedule)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  historicalsessions_.MergeFrom(from.historicalsessions_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_startdatetime(from._internal_startdatetime());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_enddatetime(from._internal_enddatetime());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_set_timezone(from._internal_timezone());
    }
    if (cached_has_bits & 0x00000008u) {
      reqid_ = from.reqid_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void HistoricalSchedule::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protobuf.HistoricalSchedule)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HistoricalSchedule::CopyFrom(const HistoricalSchedule& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.HistoricalSchedule)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HistoricalSchedule::IsInitialized() const {
  return true;
}

void HistoricalSchedule::InternalSwap(HistoricalSchedule* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  historicalsessions_.InternalSwap(&other->historicalsessions_);
  startdatetime_.Swap(&other->startdatetime_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  enddatetime_.Swap(&other->enddatetime_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  timezone_.Swap(&other->timezone_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(reqid_, other->reqid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HistoricalSchedule::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::HistoricalSchedule* Arena::CreateMaybeMessage< ::protobuf::HistoricalSchedule >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::HistoricalSchedule >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
