// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LockAndExitConfig.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_LockAndExitConfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_LockAndExitConfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_LockAndExitConfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_LockAndExitConfig_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_LockAndExitConfig_2eproto;
namespace protobuf {
class LockAndExitConfig;
class LockAndExitConfigDefaultTypeInternal;
extern LockAndExitConfigDefaultTypeInternal _LockAndExitConfig_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::protobuf::LockAndExitConfig* Arena::CreateMaybeMessage<::protobuf::LockAndExitConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf {

// ===================================================================

class LockAndExitConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.LockAndExitConfig) */ {
 public:
  inline LockAndExitConfig() : LockAndExitConfig(nullptr) {};
  virtual ~LockAndExitConfig();

  LockAndExitConfig(const LockAndExitConfig& from);
  LockAndExitConfig(LockAndExitConfig&& from) noexcept
    : LockAndExitConfig() {
    *this = ::std::move(from);
  }

  inline LockAndExitConfig& operator=(const LockAndExitConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline LockAndExitConfig& operator=(LockAndExitConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LockAndExitConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LockAndExitConfig* internal_default_instance() {
    return reinterpret_cast<const LockAndExitConfig*>(
               &_LockAndExitConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LockAndExitConfig& a, LockAndExitConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(LockAndExitConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LockAndExitConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LockAndExitConfig* New() const final {
    return CreateMaybeMessage<LockAndExitConfig>(nullptr);
  }

  LockAndExitConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LockAndExitConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LockAndExitConfig& from);
  void MergeFrom(const LockAndExitConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LockAndExitConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.LockAndExitConfig";
  }
  protected:
  explicit LockAndExitConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_LockAndExitConfig_2eproto);
    return ::descriptor_table_LockAndExitConfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAutoLogoffTimeFieldNumber = 1,
    kAutoLogoffPeriodFieldNumber = 2,
    kAutoLogoffTypeFieldNumber = 3,
  };
  // string autoLogoffTime = 1;
  bool has_autologofftime() const;
  private:
  bool _internal_has_autologofftime() const;
  public:
  void clear_autologofftime();
  const std::string& autologofftime() const;
  void set_autologofftime(const std::string& value);
  void set_autologofftime(std::string&& value);
  void set_autologofftime(const char* value);
  void set_autologofftime(const char* value, size_t size);
  std::string* mutable_autologofftime();
  std::string* release_autologofftime();
  void set_allocated_autologofftime(std::string* autologofftime);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_autologofftime();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_autologofftime(
      std::string* autologofftime);
  private:
  const std::string& _internal_autologofftime() const;
  void _internal_set_autologofftime(const std::string& value);
  std::string* _internal_mutable_autologofftime();
  public:

  // string autoLogoffPeriod = 2;
  bool has_autologoffperiod() const;
  private:
  bool _internal_has_autologoffperiod() const;
  public:
  void clear_autologoffperiod();
  const std::string& autologoffperiod() const;
  void set_autologoffperiod(const std::string& value);
  void set_autologoffperiod(std::string&& value);
  void set_autologoffperiod(const char* value);
  void set_autologoffperiod(const char* value, size_t size);
  std::string* mutable_autologoffperiod();
  std::string* release_autologoffperiod();
  void set_allocated_autologoffperiod(std::string* autologoffperiod);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_autologoffperiod();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_autologoffperiod(
      std::string* autologoffperiod);
  private:
  const std::string& _internal_autologoffperiod() const;
  void _internal_set_autologoffperiod(const std::string& value);
  std::string* _internal_mutable_autologoffperiod();
  public:

  // string autoLogoffType = 3;
  bool has_autologofftype() const;
  private:
  bool _internal_has_autologofftype() const;
  public:
  void clear_autologofftype();
  const std::string& autologofftype() const;
  void set_autologofftype(const std::string& value);
  void set_autologofftype(std::string&& value);
  void set_autologofftype(const char* value);
  void set_autologofftype(const char* value, size_t size);
  std::string* mutable_autologofftype();
  std::string* release_autologofftype();
  void set_allocated_autologofftype(std::string* autologofftype);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_autologofftype();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_autologofftype(
      std::string* autologofftype);
  private:
  const std::string& _internal_autologofftype() const;
  void _internal_set_autologofftype(const std::string& value);
  std::string* _internal_mutable_autologofftype();
  public:

  // @@protoc_insertion_point(class_scope:protobuf.LockAndExitConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr autologofftime_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr autologoffperiod_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr autologofftype_;
  friend struct ::TableStruct_LockAndExitConfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LockAndExitConfig

// string autoLogoffTime = 1;
inline bool LockAndExitConfig::_internal_has_autologofftime() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool LockAndExitConfig::has_autologofftime() const {
  return _internal_has_autologofftime();
}
inline void LockAndExitConfig::clear_autologofftime() {
  autologofftime_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& LockAndExitConfig::autologofftime() const {
  // @@protoc_insertion_point(field_get:protobuf.LockAndExitConfig.autoLogoffTime)
  return _internal_autologofftime();
}
inline void LockAndExitConfig::set_autologofftime(const std::string& value) {
  _internal_set_autologofftime(value);
  // @@protoc_insertion_point(field_set:protobuf.LockAndExitConfig.autoLogoffTime)
}
inline std::string* LockAndExitConfig::mutable_autologofftime() {
  // @@protoc_insertion_point(field_mutable:protobuf.LockAndExitConfig.autoLogoffTime)
  return _internal_mutable_autologofftime();
}
inline const std::string& LockAndExitConfig::_internal_autologofftime() const {
  return autologofftime_.Get();
}
inline void LockAndExitConfig::_internal_set_autologofftime(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  autologofftime_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LockAndExitConfig::set_autologofftime(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  autologofftime_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:protobuf.LockAndExitConfig.autoLogoffTime)
}
inline void LockAndExitConfig::set_autologofftime(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  autologofftime_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:protobuf.LockAndExitConfig.autoLogoffTime)
}
inline void LockAndExitConfig::set_autologofftime(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  autologofftime_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:protobuf.LockAndExitConfig.autoLogoffTime)
}
inline std::string* LockAndExitConfig::_internal_mutable_autologofftime() {
  _has_bits_[0] |= 0x00000001u;
  return autologofftime_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LockAndExitConfig::release_autologofftime() {
  // @@protoc_insertion_point(field_release:protobuf.LockAndExitConfig.autoLogoffTime)
  if (!_internal_has_autologofftime()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return autologofftime_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LockAndExitConfig::set_allocated_autologofftime(std::string* autologofftime) {
  if (autologofftime != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  autologofftime_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), autologofftime,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:protobuf.LockAndExitConfig.autoLogoffTime)
}
inline std::string* LockAndExitConfig::unsafe_arena_release_autologofftime() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobuf.LockAndExitConfig.autoLogoffTime)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return autologofftime_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void LockAndExitConfig::unsafe_arena_set_allocated_autologofftime(
    std::string* autologofftime) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (autologofftime != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  autologofftime_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      autologofftime, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.LockAndExitConfig.autoLogoffTime)
}

// string autoLogoffPeriod = 2;
inline bool LockAndExitConfig::_internal_has_autologoffperiod() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool LockAndExitConfig::has_autologoffperiod() const {
  return _internal_has_autologoffperiod();
}
inline void LockAndExitConfig::clear_autologoffperiod() {
  autologoffperiod_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& LockAndExitConfig::autologoffperiod() const {
  // @@protoc_insertion_point(field_get:protobuf.LockAndExitConfig.autoLogoffPeriod)
  return _internal_autologoffperiod();
}
inline void LockAndExitConfig::set_autologoffperiod(const std::string& value) {
  _internal_set_autologoffperiod(value);
  // @@protoc_insertion_point(field_set:protobuf.LockAndExitConfig.autoLogoffPeriod)
}
inline std::string* LockAndExitConfig::mutable_autologoffperiod() {
  // @@protoc_insertion_point(field_mutable:protobuf.LockAndExitConfig.autoLogoffPeriod)
  return _internal_mutable_autologoffperiod();
}
inline const std::string& LockAndExitConfig::_internal_autologoffperiod() const {
  return autologoffperiod_.Get();
}
inline void LockAndExitConfig::_internal_set_autologoffperiod(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  autologoffperiod_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LockAndExitConfig::set_autologoffperiod(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  autologoffperiod_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:protobuf.LockAndExitConfig.autoLogoffPeriod)
}
inline void LockAndExitConfig::set_autologoffperiod(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  autologoffperiod_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:protobuf.LockAndExitConfig.autoLogoffPeriod)
}
inline void LockAndExitConfig::set_autologoffperiod(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  autologoffperiod_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:protobuf.LockAndExitConfig.autoLogoffPeriod)
}
inline std::string* LockAndExitConfig::_internal_mutable_autologoffperiod() {
  _has_bits_[0] |= 0x00000002u;
  return autologoffperiod_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LockAndExitConfig::release_autologoffperiod() {
  // @@protoc_insertion_point(field_release:protobuf.LockAndExitConfig.autoLogoffPeriod)
  if (!_internal_has_autologoffperiod()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return autologoffperiod_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LockAndExitConfig::set_allocated_autologoffperiod(std::string* autologoffperiod) {
  if (autologoffperiod != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  autologoffperiod_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), autologoffperiod,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:protobuf.LockAndExitConfig.autoLogoffPeriod)
}
inline std::string* LockAndExitConfig::unsafe_arena_release_autologoffperiod() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobuf.LockAndExitConfig.autoLogoffPeriod)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000002u;
  return autologoffperiod_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void LockAndExitConfig::unsafe_arena_set_allocated_autologoffperiod(
    std::string* autologoffperiod) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (autologoffperiod != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  autologoffperiod_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      autologoffperiod, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.LockAndExitConfig.autoLogoffPeriod)
}

// string autoLogoffType = 3;
inline bool LockAndExitConfig::_internal_has_autologofftype() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool LockAndExitConfig::has_autologofftype() const {
  return _internal_has_autologofftype();
}
inline void LockAndExitConfig::clear_autologofftype() {
  autologofftype_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& LockAndExitConfig::autologofftype() const {
  // @@protoc_insertion_point(field_get:protobuf.LockAndExitConfig.autoLogoffType)
  return _internal_autologofftype();
}
inline void LockAndExitConfig::set_autologofftype(const std::string& value) {
  _internal_set_autologofftype(value);
  // @@protoc_insertion_point(field_set:protobuf.LockAndExitConfig.autoLogoffType)
}
inline std::string* LockAndExitConfig::mutable_autologofftype() {
  // @@protoc_insertion_point(field_mutable:protobuf.LockAndExitConfig.autoLogoffType)
  return _internal_mutable_autologofftype();
}
inline const std::string& LockAndExitConfig::_internal_autologofftype() const {
  return autologofftype_.Get();
}
inline void LockAndExitConfig::_internal_set_autologofftype(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  autologofftype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LockAndExitConfig::set_autologofftype(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  autologofftype_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:protobuf.LockAndExitConfig.autoLogoffType)
}
inline void LockAndExitConfig::set_autologofftype(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  autologofftype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:protobuf.LockAndExitConfig.autoLogoffType)
}
inline void LockAndExitConfig::set_autologofftype(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000004u;
  autologofftype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:protobuf.LockAndExitConfig.autoLogoffType)
}
inline std::string* LockAndExitConfig::_internal_mutable_autologofftype() {
  _has_bits_[0] |= 0x00000004u;
  return autologofftype_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LockAndExitConfig::release_autologofftype() {
  // @@protoc_insertion_point(field_release:protobuf.LockAndExitConfig.autoLogoffType)
  if (!_internal_has_autologofftype()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return autologofftype_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LockAndExitConfig::set_allocated_autologofftype(std::string* autologofftype) {
  if (autologofftype != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  autologofftype_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), autologofftype,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:protobuf.LockAndExitConfig.autoLogoffType)
}
inline std::string* LockAndExitConfig::unsafe_arena_release_autologofftype() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobuf.LockAndExitConfig.autoLogoffType)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000004u;
  return autologofftype_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void LockAndExitConfig::unsafe_arena_set_allocated_autologofftype(
    std::string* autologofftype) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (autologofftype != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  autologofftype_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      autologofftype, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.LockAndExitConfig.autoLogoffType)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_LockAndExitConfig_2eproto
