// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MarketDepthExchanges.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MarketDepthExchanges_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MarketDepthExchanges_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "DepthMarketDataDescription.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MarketDepthExchanges_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MarketDepthExchanges_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MarketDepthExchanges_2eproto;
namespace protobuf {
class MarketDepthExchanges;
class MarketDepthExchangesDefaultTypeInternal;
extern MarketDepthExchangesDefaultTypeInternal _MarketDepthExchanges_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::protobuf::MarketDepthExchanges* Arena::CreateMaybeMessage<::protobuf::MarketDepthExchanges>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf {

// ===================================================================

class MarketDepthExchanges PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.MarketDepthExchanges) */ {
 public:
  inline MarketDepthExchanges() : MarketDepthExchanges(nullptr) {};
  virtual ~MarketDepthExchanges();

  MarketDepthExchanges(const MarketDepthExchanges& from);
  MarketDepthExchanges(MarketDepthExchanges&& from) noexcept
    : MarketDepthExchanges() {
    *this = ::std::move(from);
  }

  inline MarketDepthExchanges& operator=(const MarketDepthExchanges& from) {
    CopyFrom(from);
    return *this;
  }
  inline MarketDepthExchanges& operator=(MarketDepthExchanges&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MarketDepthExchanges& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MarketDepthExchanges* internal_default_instance() {
    return reinterpret_cast<const MarketDepthExchanges*>(
               &_MarketDepthExchanges_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MarketDepthExchanges& a, MarketDepthExchanges& b) {
    a.Swap(&b);
  }
  inline void Swap(MarketDepthExchanges* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MarketDepthExchanges* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MarketDepthExchanges* New() const final {
    return CreateMaybeMessage<MarketDepthExchanges>(nullptr);
  }

  MarketDepthExchanges* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MarketDepthExchanges>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MarketDepthExchanges& from);
  void MergeFrom(const MarketDepthExchanges& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MarketDepthExchanges* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.MarketDepthExchanges";
  }
  protected:
  explicit MarketDepthExchanges(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MarketDepthExchanges_2eproto);
    return ::descriptor_table_MarketDepthExchanges_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDepthMarketDataDescriptionsFieldNumber = 1,
  };
  // repeated .protobuf.DepthMarketDataDescription depthMarketDataDescriptions = 1;
  int depthmarketdatadescriptions_size() const;
  private:
  int _internal_depthmarketdatadescriptions_size() const;
  public:
  void clear_depthmarketdatadescriptions();
  ::protobuf::DepthMarketDataDescription* mutable_depthmarketdatadescriptions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::DepthMarketDataDescription >*
      mutable_depthmarketdatadescriptions();
  private:
  const ::protobuf::DepthMarketDataDescription& _internal_depthmarketdatadescriptions(int index) const;
  ::protobuf::DepthMarketDataDescription* _internal_add_depthmarketdatadescriptions();
  public:
  const ::protobuf::DepthMarketDataDescription& depthmarketdatadescriptions(int index) const;
  ::protobuf::DepthMarketDataDescription* add_depthmarketdatadescriptions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::DepthMarketDataDescription >&
      depthmarketdatadescriptions() const;

  // @@protoc_insertion_point(class_scope:protobuf.MarketDepthExchanges)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::DepthMarketDataDescription > depthmarketdatadescriptions_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MarketDepthExchanges_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MarketDepthExchanges

// repeated .protobuf.DepthMarketDataDescription depthMarketDataDescriptions = 1;
inline int MarketDepthExchanges::_internal_depthmarketdatadescriptions_size() const {
  return depthmarketdatadescriptions_.size();
}
inline int MarketDepthExchanges::depthmarketdatadescriptions_size() const {
  return _internal_depthmarketdatadescriptions_size();
}
inline ::protobuf::DepthMarketDataDescription* MarketDepthExchanges::mutable_depthmarketdatadescriptions(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf.MarketDepthExchanges.depthMarketDataDescriptions)
  return depthmarketdatadescriptions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::DepthMarketDataDescription >*
MarketDepthExchanges::mutable_depthmarketdatadescriptions() {
  // @@protoc_insertion_point(field_mutable_list:protobuf.MarketDepthExchanges.depthMarketDataDescriptions)
  return &depthmarketdatadescriptions_;
}
inline const ::protobuf::DepthMarketDataDescription& MarketDepthExchanges::_internal_depthmarketdatadescriptions(int index) const {
  return depthmarketdatadescriptions_.Get(index);
}
inline const ::protobuf::DepthMarketDataDescription& MarketDepthExchanges::depthmarketdatadescriptions(int index) const {
  // @@protoc_insertion_point(field_get:protobuf.MarketDepthExchanges.depthMarketDataDescriptions)
  return _internal_depthmarketdatadescriptions(index);
}
inline ::protobuf::DepthMarketDataDescription* MarketDepthExchanges::_internal_add_depthmarketdatadescriptions() {
  return depthmarketdatadescriptions_.Add();
}
inline ::protobuf::DepthMarketDataDescription* MarketDepthExchanges::add_depthmarketdatadescriptions() {
  // @@protoc_insertion_point(field_add:protobuf.MarketDepthExchanges.depthMarketDataDescriptions)
  return _internal_add_depthmarketdatadescriptions();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::DepthMarketDataDescription >&
MarketDepthExchanges::depthmarketdatadescriptions() const {
  // @@protoc_insertion_point(field_list:protobuf.MarketDepthExchanges.depthMarketDataDescriptions)
  return depthmarketdatadescriptions_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MarketDepthExchanges_2eproto
