// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MarketDepthExchanges.proto

#include "MarketDepthExchanges.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_DepthMarketDataDescription_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DepthMarketDataDescription_DepthMarketDataDescription_2eproto;
namespace protobuf {
class MarketDepthExchangesDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MarketDepthExchanges> _instance;
} _MarketDepthExchanges_default_instance_;
}  // namespace protobuf
static void InitDefaultsscc_info_MarketDepthExchanges_MarketDepthExchanges_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protobuf::_MarketDepthExchanges_default_instance_;
    new (ptr) ::protobuf::MarketDepthExchanges();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protobuf::MarketDepthExchanges::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MarketDepthExchanges_MarketDepthExchanges_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_MarketDepthExchanges_MarketDepthExchanges_2eproto}, {
      &scc_info_DepthMarketDataDescription_DepthMarketDataDescription_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_MarketDepthExchanges_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_MarketDepthExchanges_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_MarketDepthExchanges_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_MarketDepthExchanges_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::MarketDepthExchanges, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protobuf::MarketDepthExchanges, depthmarketdatadescriptions_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::protobuf::MarketDepthExchanges)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_MarketDepthExchanges_default_instance_),
};

const char descriptor_table_protodef_MarketDepthExchanges_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032MarketDepthExchanges.proto\022\010protobuf\032 "
  "DepthMarketDataDescription.proto\"a\n\024Mark"
  "etDepthExchanges\022I\n\033depthMarketDataDescr"
  "iptions\030\001 \003(\0132$.protobuf.DepthMarketData"
  "DescriptionBD\n\026com.ib.client.protobufB\031M"
  "arketDepthExchangesProto\252\002\016IBApi.protobu"
  "fb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_MarketDepthExchanges_2eproto_deps[1] = {
  &::descriptor_table_DepthMarketDataDescription_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_MarketDepthExchanges_2eproto_sccs[1] = {
  &scc_info_MarketDepthExchanges_MarketDepthExchanges_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_MarketDepthExchanges_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MarketDepthExchanges_2eproto = {
  false, false, descriptor_table_protodef_MarketDepthExchanges_2eproto, "MarketDepthExchanges.proto", 249,
  &descriptor_table_MarketDepthExchanges_2eproto_once, descriptor_table_MarketDepthExchanges_2eproto_sccs, descriptor_table_MarketDepthExchanges_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_MarketDepthExchanges_2eproto::offsets,
  file_level_metadata_MarketDepthExchanges_2eproto, 1, file_level_enum_descriptors_MarketDepthExchanges_2eproto, file_level_service_descriptors_MarketDepthExchanges_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_MarketDepthExchanges_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_MarketDepthExchanges_2eproto)), true);
namespace protobuf {

// ===================================================================

void MarketDepthExchanges::InitAsDefaultInstance() {
}
class MarketDepthExchanges::_Internal {
 public:
};

void MarketDepthExchanges::clear_depthmarketdatadescriptions() {
  depthmarketdatadescriptions_.Clear();
}
MarketDepthExchanges::MarketDepthExchanges(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  depthmarketdatadescriptions_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.MarketDepthExchanges)
}
MarketDepthExchanges::MarketDepthExchanges(const MarketDepthExchanges& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      depthmarketdatadescriptions_(from.depthmarketdatadescriptions_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.MarketDepthExchanges)
}

void MarketDepthExchanges::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MarketDepthExchanges_MarketDepthExchanges_2eproto.base);
}

MarketDepthExchanges::~MarketDepthExchanges() {
  // @@protoc_insertion_point(destructor:protobuf.MarketDepthExchanges)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MarketDepthExchanges::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void MarketDepthExchanges::ArenaDtor(void* object) {
  MarketDepthExchanges* _this = reinterpret_cast< MarketDepthExchanges* >(object);
  (void)_this;
}
void MarketDepthExchanges::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MarketDepthExchanges::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MarketDepthExchanges& MarketDepthExchanges::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MarketDepthExchanges_MarketDepthExchanges_2eproto.base);
  return *internal_default_instance();
}


void MarketDepthExchanges::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.MarketDepthExchanges)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  depthmarketdatadescriptions_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MarketDepthExchanges::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .protobuf.DepthMarketDataDescription depthMarketDataDescriptions = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_depthmarketdatadescriptions(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MarketDepthExchanges::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.MarketDepthExchanges)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .protobuf.DepthMarketDataDescription depthMarketDataDescriptions = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_depthmarketdatadescriptions_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_depthmarketdatadescriptions(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.MarketDepthExchanges)
  return target;
}

size_t MarketDepthExchanges::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.MarketDepthExchanges)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .protobuf.DepthMarketDataDescription depthMarketDataDescriptions = 1;
  total_size += 1UL * this->_internal_depthmarketdatadescriptions_size();
  for (const auto& msg : this->depthmarketdatadescriptions_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MarketDepthExchanges::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protobuf.MarketDepthExchanges)
  GOOGLE_DCHECK_NE(&from, this);
  const MarketDepthExchanges* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MarketDepthExchanges>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protobuf.MarketDepthExchanges)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protobuf.MarketDepthExchanges)
    MergeFrom(*source);
  }
}

void MarketDepthExchanges::MergeFrom(const MarketDepthExchanges& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.MarketDepthExchanges)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  depthmarketdatadescriptions_.MergeFrom(from.depthmarketdatadescriptions_);
}

void MarketDepthExchanges::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protobuf.MarketDepthExchanges)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MarketDepthExchanges::CopyFrom(const MarketDepthExchanges& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.MarketDepthExchanges)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MarketDepthExchanges::IsInitialized() const {
  return true;
}

void MarketDepthExchanges::InternalSwap(MarketDepthExchanges* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  depthmarketdatadescriptions_.InternalSwap(&other->depthmarketdatadescriptions_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MarketDepthExchanges::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::MarketDepthExchanges* Arena::CreateMaybeMessage< ::protobuf::MarketDepthExchanges >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::MarketDepthExchanges >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
