// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsBulletin.proto

#include "NewsBulletin.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace protobuf {
class NewsBulletinDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NewsBulletin> _instance;
} _NewsBulletin_default_instance_;
}  // namespace protobuf
static void InitDefaultsscc_info_NewsBulletin_NewsBulletin_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protobuf::_NewsBulletin_default_instance_;
    new (ptr) ::protobuf::NewsBulletin();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protobuf::NewsBulletin::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NewsBulletin_NewsBulletin_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_NewsBulletin_NewsBulletin_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_NewsBulletin_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_NewsBulletin_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_NewsBulletin_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_NewsBulletin_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::protobuf::NewsBulletin, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protobuf::NewsBulletin, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protobuf::NewsBulletin, newsmsgid_),
  PROTOBUF_FIELD_OFFSET(::protobuf::NewsBulletin, newsmsgtype_),
  PROTOBUF_FIELD_OFFSET(::protobuf::NewsBulletin, newsmessage_),
  PROTOBUF_FIELD_OFFSET(::protobuf::NewsBulletin, originatingexch_),
  2,
  3,
  0,
  1,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, sizeof(::protobuf::NewsBulletin)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_NewsBulletin_default_instance_),
};

const char descriptor_table_protodef_NewsBulletin_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022NewsBulletin.proto\022\010protobuf\"\272\001\n\014NewsB"
  "ulletin\022\026\n\tnewsMsgId\030\001 \001(\005H\000\210\001\001\022\030\n\013newsM"
  "sgType\030\002 \001(\005H\001\210\001\001\022\030\n\013newsMessage\030\003 \001(\tH\002"
  "\210\001\001\022\034\n\017originatingExch\030\004 \001(\tH\003\210\001\001B\014\n\n_ne"
  "wsMsgIdB\016\n\014_newsMsgTypeB\016\n\014_newsMessageB"
  "\022\n\020_originatingExchB<\n\026com.ib.client.pro"
  "tobufB\021NewsBulletinProto\252\002\016IBApi.protobu"
  "fb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_NewsBulletin_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_NewsBulletin_2eproto_sccs[1] = {
  &scc_info_NewsBulletin_NewsBulletin_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_NewsBulletin_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_NewsBulletin_2eproto = {
  false, false, descriptor_table_protodef_NewsBulletin_2eproto, "NewsBulletin.proto", 289,
  &descriptor_table_NewsBulletin_2eproto_once, descriptor_table_NewsBulletin_2eproto_sccs, descriptor_table_NewsBulletin_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_NewsBulletin_2eproto::offsets,
  file_level_metadata_NewsBulletin_2eproto, 1, file_level_enum_descriptors_NewsBulletin_2eproto, file_level_service_descriptors_NewsBulletin_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_NewsBulletin_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_NewsBulletin_2eproto)), true);
namespace protobuf {

// ===================================================================

void NewsBulletin::InitAsDefaultInstance() {
}
class NewsBulletin::_Internal {
 public:
  using HasBits = decltype(std::declval<NewsBulletin>()._has_bits_);
  static void set_has_newsmsgid(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_newsmsgtype(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_newsmessage(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_originatingexch(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

NewsBulletin::NewsBulletin(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.NewsBulletin)
}
NewsBulletin::NewsBulletin(const NewsBulletin& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  newsmessage_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_newsmessage()) {
    newsmessage_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_newsmessage(),
      GetArena());
  }
  originatingexch_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_originatingexch()) {
    originatingexch_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_originatingexch(),
      GetArena());
  }
  ::memcpy(&newsmsgid_, &from.newsmsgid_,
    static_cast<size_t>(reinterpret_cast<char*>(&newsmsgtype_) -
    reinterpret_cast<char*>(&newsmsgid_)) + sizeof(newsmsgtype_));
  // @@protoc_insertion_point(copy_constructor:protobuf.NewsBulletin)
}

void NewsBulletin::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NewsBulletin_NewsBulletin_2eproto.base);
  newsmessage_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  originatingexch_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&newsmsgid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&newsmsgtype_) -
      reinterpret_cast<char*>(&newsmsgid_)) + sizeof(newsmsgtype_));
}

NewsBulletin::~NewsBulletin() {
  // @@protoc_insertion_point(destructor:protobuf.NewsBulletin)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NewsBulletin::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  newsmessage_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  originatingexch_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NewsBulletin::ArenaDtor(void* object) {
  NewsBulletin* _this = reinterpret_cast< NewsBulletin* >(object);
  (void)_this;
}
void NewsBulletin::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NewsBulletin::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NewsBulletin& NewsBulletin::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NewsBulletin_NewsBulletin_2eproto.base);
  return *internal_default_instance();
}


void NewsBulletin::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.NewsBulletin)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      newsmessage_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      originatingexch_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000000cu) {
    ::memset(&newsmsgid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&newsmsgtype_) -
        reinterpret_cast<char*>(&newsmsgid_)) + sizeof(newsmsgtype_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NewsBulletin::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 newsMsgId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_newsmsgid(&has_bits);
          newsmsgid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 newsMsgType = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_newsmsgtype(&has_bits);
          newsmsgtype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string newsMessage = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_newsmessage();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.NewsBulletin.newsMessage"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string originatingExch = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_originatingexch();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.NewsBulletin.originatingExch"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NewsBulletin::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.NewsBulletin)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 newsMsgId = 1;
  if (_internal_has_newsmsgid()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_newsmsgid(), target);
  }

  // int32 newsMsgType = 2;
  if (_internal_has_newsmsgtype()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_newsmsgtype(), target);
  }

  // string newsMessage = 3;
  if (_internal_has_newsmessage()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_newsmessage().data(), static_cast<int>(this->_internal_newsmessage().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.NewsBulletin.newsMessage");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_newsmessage(), target);
  }

  // string originatingExch = 4;
  if (_internal_has_originatingexch()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_originatingexch().data(), static_cast<int>(this->_internal_originatingexch().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.NewsBulletin.originatingExch");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_originatingexch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.NewsBulletin)
  return target;
}

size_t NewsBulletin::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.NewsBulletin)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // string newsMessage = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_newsmessage());
    }

    // string originatingExch = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_originatingexch());
    }

    // int32 newsMsgId = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_newsmsgid());
    }

    // int32 newsMsgType = 2;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_newsmsgtype());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NewsBulletin::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protobuf.NewsBulletin)
  GOOGLE_DCHECK_NE(&from, this);
  const NewsBulletin* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<NewsBulletin>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protobuf.NewsBulletin)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protobuf.NewsBulletin)
    MergeFrom(*source);
  }
}

void NewsBulletin::MergeFrom(const NewsBulletin& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.NewsBulletin)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_newsmessage(from._internal_newsmessage());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_originatingexch(from._internal_originatingexch());
    }
    if (cached_has_bits & 0x00000004u) {
      newsmsgid_ = from.newsmsgid_;
    }
    if (cached_has_bits & 0x00000008u) {
      newsmsgtype_ = from.newsmsgtype_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void NewsBulletin::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protobuf.NewsBulletin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NewsBulletin::CopyFrom(const NewsBulletin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.NewsBulletin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NewsBulletin::IsInitialized() const {
  return true;
}

void NewsBulletin::InternalSwap(NewsBulletin* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  newsmessage_.Swap(&other->newsmessage_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  originatingexch_.Swap(&other->originatingexch_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NewsBulletin, newsmsgtype_)
      + sizeof(NewsBulletin::newsmsgtype_)
      - PROTOBUF_FIELD_OFFSET(NewsBulletin, newsmsgid_)>(
          reinterpret_cast<char*>(&newsmsgid_),
          reinterpret_cast<char*>(&other->newsmsgid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata NewsBulletin::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::NewsBulletin* Arena::CreateMaybeMessage< ::protobuf::NewsBulletin >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::NewsBulletin >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
