// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsProvider.proto

#include "NewsProvider.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace protobuf {
class NewsProviderDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NewsProvider> _instance;
} _NewsProvider_default_instance_;
}  // namespace protobuf
static void InitDefaultsscc_info_NewsProvider_NewsProvider_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protobuf::_NewsProvider_default_instance_;
    new (ptr) ::protobuf::NewsProvider();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protobuf::NewsProvider::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NewsProvider_NewsProvider_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_NewsProvider_NewsProvider_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_NewsProvider_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_NewsProvider_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_NewsProvider_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_NewsProvider_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::protobuf::NewsProvider, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protobuf::NewsProvider, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protobuf::NewsProvider, providercode_),
  PROTOBUF_FIELD_OFFSET(::protobuf::NewsProvider, providername_),
  0,
  1,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::protobuf::NewsProvider)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_NewsProvider_default_instance_),
};

const char descriptor_table_protodef_NewsProvider_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022NewsProvider.proto\022\010protobuf\"f\n\014NewsPr"
  "ovider\022\031\n\014providerCode\030\001 \001(\tH\000\210\001\001\022\031\n\014pro"
  "viderName\030\002 \001(\tH\001\210\001\001B\017\n\r_providerCodeB\017\n"
  "\r_providerNameB<\n\026com.ib.client.protobuf"
  "B\021NewsProviderProto\252\002\016IBApi.protobufb\006pr"
  "oto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_NewsProvider_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_NewsProvider_2eproto_sccs[1] = {
  &scc_info_NewsProvider_NewsProvider_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_NewsProvider_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_NewsProvider_2eproto = {
  false, false, descriptor_table_protodef_NewsProvider_2eproto, "NewsProvider.proto", 204,
  &descriptor_table_NewsProvider_2eproto_once, descriptor_table_NewsProvider_2eproto_sccs, descriptor_table_NewsProvider_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_NewsProvider_2eproto::offsets,
  file_level_metadata_NewsProvider_2eproto, 1, file_level_enum_descriptors_NewsProvider_2eproto, file_level_service_descriptors_NewsProvider_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_NewsProvider_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_NewsProvider_2eproto)), true);
namespace protobuf {

// ===================================================================

void NewsProvider::InitAsDefaultInstance() {
}
class NewsProvider::_Internal {
 public:
  using HasBits = decltype(std::declval<NewsProvider>()._has_bits_);
  static void set_has_providercode(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_providername(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

NewsProvider::NewsProvider(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.NewsProvider)
}
NewsProvider::NewsProvider(const NewsProvider& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  providercode_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_providercode()) {
    providercode_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_providercode(),
      GetArena());
  }
  providername_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_providername()) {
    providername_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_providername(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:protobuf.NewsProvider)
}

void NewsProvider::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NewsProvider_NewsProvider_2eproto.base);
  providercode_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  providername_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

NewsProvider::~NewsProvider() {
  // @@protoc_insertion_point(destructor:protobuf.NewsProvider)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NewsProvider::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  providercode_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  providername_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NewsProvider::ArenaDtor(void* object) {
  NewsProvider* _this = reinterpret_cast< NewsProvider* >(object);
  (void)_this;
}
void NewsProvider::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NewsProvider::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NewsProvider& NewsProvider::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NewsProvider_NewsProvider_2eproto.base);
  return *internal_default_instance();
}


void NewsProvider::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.NewsProvider)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      providercode_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      providername_.ClearNonDefaultToEmpty();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NewsProvider::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string providerCode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_providercode();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.NewsProvider.providerCode"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string providerName = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_providername();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.NewsProvider.providerName"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NewsProvider::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.NewsProvider)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string providerCode = 1;
  if (_internal_has_providercode()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_providercode().data(), static_cast<int>(this->_internal_providercode().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.NewsProvider.providerCode");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_providercode(), target);
  }

  // string providerName = 2;
  if (_internal_has_providername()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_providername().data(), static_cast<int>(this->_internal_providername().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.NewsProvider.providerName");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_providername(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.NewsProvider)
  return target;
}

size_t NewsProvider::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.NewsProvider)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // string providerCode = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_providercode());
    }

    // string providerName = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_providername());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NewsProvider::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protobuf.NewsProvider)
  GOOGLE_DCHECK_NE(&from, this);
  const NewsProvider* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<NewsProvider>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protobuf.NewsProvider)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protobuf.NewsProvider)
    MergeFrom(*source);
  }
}

void NewsProvider::MergeFrom(const NewsProvider& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.NewsProvider)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_providercode(from._internal_providercode());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_providername(from._internal_providername());
    }
  }
}

void NewsProvider::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protobuf.NewsProvider)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NewsProvider::CopyFrom(const NewsProvider& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.NewsProvider)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NewsProvider::IsInitialized() const {
  return true;
}

void NewsProvider::InternalSwap(NewsProvider* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  providercode_.Swap(&other->providercode_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  providername_.Swap(&other->providername_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata NewsProvider::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::NewsProvider* Arena::CreateMaybeMessage< ::protobuf::NewsProvider >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::NewsProvider >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
