// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PortfolioValue.proto

#include "PortfolioValue.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_Contract_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_Contract_Contract_2eproto;
namespace protobuf {
class PortfolioValueDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PortfolioValue> _instance;
} _PortfolioValue_default_instance_;
}  // namespace protobuf
static void InitDefaultsscc_info_PortfolioValue_PortfolioValue_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protobuf::_PortfolioValue_default_instance_;
    new (ptr) ::protobuf::PortfolioValue();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protobuf::PortfolioValue::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_PortfolioValue_PortfolioValue_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_PortfolioValue_PortfolioValue_2eproto}, {
      &scc_info_Contract_Contract_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_PortfolioValue_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_PortfolioValue_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_PortfolioValue_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_PortfolioValue_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, contract_),
  PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, position_),
  PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, marketprice_),
  PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, marketvalue_),
  PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, averagecost_),
  PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, unrealizedpnl_),
  PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, realizedpnl_),
  PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, accountname_),
  2,
  0,
  3,
  4,
  5,
  6,
  7,
  1,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 13, sizeof(::protobuf::PortfolioValue)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_PortfolioValue_default_instance_),
};

const char descriptor_table_protodef_PortfolioValue_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024PortfolioValue.proto\022\010protobuf\032\016Contra"
  "ct.proto\"\354\002\n\016PortfolioValue\022)\n\010contract\030"
  "\001 \001(\0132\022.protobuf.ContractH\000\210\001\001\022\025\n\010positi"
  "on\030\002 \001(\tH\001\210\001\001\022\030\n\013marketPrice\030\003 \001(\001H\002\210\001\001\022"
  "\030\n\013marketValue\030\004 \001(\001H\003\210\001\001\022\030\n\013averageCost"
  "\030\005 \001(\001H\004\210\001\001\022\032\n\runrealizedPNL\030\006 \001(\001H\005\210\001\001\022"
  "\030\n\013realizedPNL\030\007 \001(\001H\006\210\001\001\022\030\n\013accountName"
  "\030\010 \001(\tH\007\210\001\001B\013\n\t_contractB\013\n\t_positionB\016\n"
  "\014_marketPriceB\016\n\014_marketValueB\016\n\014_averag"
  "eCostB\020\n\016_unrealizedPNLB\016\n\014_realizedPNLB"
  "\016\n\014_accountNameB>\n\026com.ib.client.protobu"
  "fB\023PortfolioValueProto\252\002\016IBApi.protobufb"
  "\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_PortfolioValue_2eproto_deps[1] = {
  &::descriptor_table_Contract_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_PortfolioValue_2eproto_sccs[1] = {
  &scc_info_PortfolioValue_PortfolioValue_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_PortfolioValue_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PortfolioValue_2eproto = {
  false, false, descriptor_table_protodef_PortfolioValue_2eproto, "PortfolioValue.proto", 487,
  &descriptor_table_PortfolioValue_2eproto_once, descriptor_table_PortfolioValue_2eproto_sccs, descriptor_table_PortfolioValue_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_PortfolioValue_2eproto::offsets,
  file_level_metadata_PortfolioValue_2eproto, 1, file_level_enum_descriptors_PortfolioValue_2eproto, file_level_service_descriptors_PortfolioValue_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_PortfolioValue_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_PortfolioValue_2eproto)), true);
namespace protobuf {

// ===================================================================

void PortfolioValue::InitAsDefaultInstance() {
  ::protobuf::_PortfolioValue_default_instance_._instance.get_mutable()->contract_ = const_cast< ::protobuf::Contract*>(
      ::protobuf::Contract::internal_default_instance());
}
class PortfolioValue::_Internal {
 public:
  using HasBits = decltype(std::declval<PortfolioValue>()._has_bits_);
  static const ::protobuf::Contract& contract(const PortfolioValue* msg);
  static void set_has_contract(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_position(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_marketprice(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_marketvalue(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_averagecost(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_unrealizedpnl(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_realizedpnl(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_accountname(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::protobuf::Contract&
PortfolioValue::_Internal::contract(const PortfolioValue* msg) {
  return *msg->contract_;
}
void PortfolioValue::clear_contract() {
  if (GetArena() == nullptr && contract_ != nullptr) {
    delete contract_;
  }
  contract_ = nullptr;
  _has_bits_[0] &= ~0x00000004u;
}
PortfolioValue::PortfolioValue(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.PortfolioValue)
}
PortfolioValue::PortfolioValue(const PortfolioValue& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  position_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_position()) {
    position_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_position(),
      GetArena());
  }
  accountname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_accountname()) {
    accountname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_accountname(),
      GetArena());
  }
  if (from._internal_has_contract()) {
    contract_ = new ::protobuf::Contract(*from.contract_);
  } else {
    contract_ = nullptr;
  }
  ::memcpy(&marketprice_, &from.marketprice_,
    static_cast<size_t>(reinterpret_cast<char*>(&realizedpnl_) -
    reinterpret_cast<char*>(&marketprice_)) + sizeof(realizedpnl_));
  // @@protoc_insertion_point(copy_constructor:protobuf.PortfolioValue)
}

void PortfolioValue::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PortfolioValue_PortfolioValue_2eproto.base);
  position_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  accountname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&contract_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&realizedpnl_) -
      reinterpret_cast<char*>(&contract_)) + sizeof(realizedpnl_));
}

PortfolioValue::~PortfolioValue() {
  // @@protoc_insertion_point(destructor:protobuf.PortfolioValue)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PortfolioValue::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  position_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  accountname_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete contract_;
}

void PortfolioValue::ArenaDtor(void* object) {
  PortfolioValue* _this = reinterpret_cast< PortfolioValue* >(object);
  (void)_this;
}
void PortfolioValue::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PortfolioValue::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PortfolioValue& PortfolioValue::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PortfolioValue_PortfolioValue_2eproto.base);
  return *internal_default_instance();
}


void PortfolioValue::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.PortfolioValue)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      position_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      accountname_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      if (GetArena() == nullptr && contract_ != nullptr) {
        delete contract_;
      }
      contract_ = nullptr;
    }
  }
  if (cached_has_bits & 0x000000f8u) {
    ::memset(&marketprice_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&realizedpnl_) -
        reinterpret_cast<char*>(&marketprice_)) + sizeof(realizedpnl_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PortfolioValue::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .protobuf.Contract contract = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_contract(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string position = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_position();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.PortfolioValue.position"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double marketPrice = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          _Internal::set_has_marketprice(&has_bits);
          marketprice_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double marketValue = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          _Internal::set_has_marketvalue(&has_bits);
          marketvalue_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double averageCost = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 41)) {
          _Internal::set_has_averagecost(&has_bits);
          averagecost_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double unrealizedPNL = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          _Internal::set_has_unrealizedpnl(&has_bits);
          unrealizedpnl_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double realizedPNL = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 57)) {
          _Internal::set_has_realizedpnl(&has_bits);
          realizedpnl_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // string accountName = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          auto str = _internal_mutable_accountname();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.PortfolioValue.accountName"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PortfolioValue::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.PortfolioValue)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .protobuf.Contract contract = 1;
  if (_internal_has_contract()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::contract(this), target, stream);
  }

  // string position = 2;
  if (_internal_has_position()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_position().data(), static_cast<int>(this->_internal_position().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.PortfolioValue.position");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_position(), target);
  }

  // double marketPrice = 3;
  if (_internal_has_marketprice()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_marketprice(), target);
  }

  // double marketValue = 4;
  if (_internal_has_marketvalue()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_marketvalue(), target);
  }

  // double averageCost = 5;
  if (_internal_has_averagecost()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(5, this->_internal_averagecost(), target);
  }

  // double unrealizedPNL = 6;
  if (_internal_has_unrealizedpnl()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->_internal_unrealizedpnl(), target);
  }

  // double realizedPNL = 7;
  if (_internal_has_realizedpnl()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(7, this->_internal_realizedpnl(), target);
  }

  // string accountName = 8;
  if (_internal_has_accountname()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_accountname().data(), static_cast<int>(this->_internal_accountname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.PortfolioValue.accountName");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_accountname(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.PortfolioValue)
  return target;
}

size_t PortfolioValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.PortfolioValue)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // string position = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_position());
    }

    // string accountName = 8;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_accountname());
    }

    // .protobuf.Contract contract = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *contract_);
    }

    // double marketPrice = 3;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 8;
    }

    // double marketValue = 4;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 8;
    }

    // double averageCost = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 8;
    }

    // double unrealizedPNL = 6;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + 8;
    }

    // double realizedPNL = 7;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 + 8;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PortfolioValue::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protobuf.PortfolioValue)
  GOOGLE_DCHECK_NE(&from, this);
  const PortfolioValue* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PortfolioValue>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protobuf.PortfolioValue)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protobuf.PortfolioValue)
    MergeFrom(*source);
  }
}

void PortfolioValue::MergeFrom(const PortfolioValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.PortfolioValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_position(from._internal_position());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_accountname(from._internal_accountname());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_contract()->::protobuf::Contract::MergeFrom(from._internal_contract());
    }
    if (cached_has_bits & 0x00000008u) {
      marketprice_ = from.marketprice_;
    }
    if (cached_has_bits & 0x00000010u) {
      marketvalue_ = from.marketvalue_;
    }
    if (cached_has_bits & 0x00000020u) {
      averagecost_ = from.averagecost_;
    }
    if (cached_has_bits & 0x00000040u) {
      unrealizedpnl_ = from.unrealizedpnl_;
    }
    if (cached_has_bits & 0x00000080u) {
      realizedpnl_ = from.realizedpnl_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void PortfolioValue::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protobuf.PortfolioValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PortfolioValue::CopyFrom(const PortfolioValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.PortfolioValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PortfolioValue::IsInitialized() const {
  return true;
}

void PortfolioValue::InternalSwap(PortfolioValue* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  position_.Swap(&other->position_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  accountname_.Swap(&other->accountname_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PortfolioValue, realizedpnl_)
      + sizeof(PortfolioValue::realizedpnl_)
      - PROTOBUF_FIELD_OFFSET(PortfolioValue, contract_)>(
          reinterpret_cast<char*>(&contract_),
          reinterpret_cast<char*>(&other->contract_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PortfolioValue::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::PortfolioValue* Arena::CreateMaybeMessage< ::protobuf::PortfolioValue >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::PortfolioValue >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
