// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SoftDollarTiers.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SoftDollarTiers_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SoftDollarTiers_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "SoftDollarTier.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SoftDollarTiers_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SoftDollarTiers_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SoftDollarTiers_2eproto;
namespace protobuf {
class SoftDollarTiers;
class SoftDollarTiersDefaultTypeInternal;
extern SoftDollarTiersDefaultTypeInternal _SoftDollarTiers_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::protobuf::SoftDollarTiers* Arena::CreateMaybeMessage<::protobuf::SoftDollarTiers>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf {

// ===================================================================

class SoftDollarTiers PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.SoftDollarTiers) */ {
 public:
  inline SoftDollarTiers() : SoftDollarTiers(nullptr) {};
  virtual ~SoftDollarTiers();

  SoftDollarTiers(const SoftDollarTiers& from);
  SoftDollarTiers(SoftDollarTiers&& from) noexcept
    : SoftDollarTiers() {
    *this = ::std::move(from);
  }

  inline SoftDollarTiers& operator=(const SoftDollarTiers& from) {
    CopyFrom(from);
    return *this;
  }
  inline SoftDollarTiers& operator=(SoftDollarTiers&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SoftDollarTiers& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SoftDollarTiers* internal_default_instance() {
    return reinterpret_cast<const SoftDollarTiers*>(
               &_SoftDollarTiers_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SoftDollarTiers& a, SoftDollarTiers& b) {
    a.Swap(&b);
  }
  inline void Swap(SoftDollarTiers* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SoftDollarTiers* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SoftDollarTiers* New() const final {
    return CreateMaybeMessage<SoftDollarTiers>(nullptr);
  }

  SoftDollarTiers* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SoftDollarTiers>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SoftDollarTiers& from);
  void MergeFrom(const SoftDollarTiers& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SoftDollarTiers* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.SoftDollarTiers";
  }
  protected:
  explicit SoftDollarTiers(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_SoftDollarTiers_2eproto);
    return ::descriptor_table_SoftDollarTiers_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSoftDollarTiersFieldNumber = 2,
    kReqIdFieldNumber = 1,
  };
  // repeated .protobuf.SoftDollarTier softDollarTiers = 2;
  int softdollartiers_size() const;
  private:
  int _internal_softdollartiers_size() const;
  public:
  void clear_softdollartiers();
  ::protobuf::SoftDollarTier* mutable_softdollartiers(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::SoftDollarTier >*
      mutable_softdollartiers();
  private:
  const ::protobuf::SoftDollarTier& _internal_softdollartiers(int index) const;
  ::protobuf::SoftDollarTier* _internal_add_softdollartiers();
  public:
  const ::protobuf::SoftDollarTier& softdollartiers(int index) const;
  ::protobuf::SoftDollarTier* add_softdollartiers();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::SoftDollarTier >&
      softdollartiers() const;

  // int32 reqId = 1;
  bool has_reqid() const;
  private:
  bool _internal_has_reqid() const;
  public:
  void clear_reqid();
  ::PROTOBUF_NAMESPACE_ID::int32 reqid() const;
  void set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_reqid() const;
  void _internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protobuf.SoftDollarTiers)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::SoftDollarTier > softdollartiers_;
  ::PROTOBUF_NAMESPACE_ID::int32 reqid_;
  friend struct ::TableStruct_SoftDollarTiers_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SoftDollarTiers

// int32 reqId = 1;
inline bool SoftDollarTiers::_internal_has_reqid() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SoftDollarTiers::has_reqid() const {
  return _internal_has_reqid();
}
inline void SoftDollarTiers::clear_reqid() {
  reqid_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SoftDollarTiers::_internal_reqid() const {
  return reqid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SoftDollarTiers::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.SoftDollarTiers.reqId)
  return _internal_reqid();
}
inline void SoftDollarTiers::_internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  reqid_ = value;
}
inline void SoftDollarTiers::set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_reqid(value);
  // @@protoc_insertion_point(field_set:protobuf.SoftDollarTiers.reqId)
}

// repeated .protobuf.SoftDollarTier softDollarTiers = 2;
inline int SoftDollarTiers::_internal_softdollartiers_size() const {
  return softdollartiers_.size();
}
inline int SoftDollarTiers::softdollartiers_size() const {
  return _internal_softdollartiers_size();
}
inline ::protobuf::SoftDollarTier* SoftDollarTiers::mutable_softdollartiers(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf.SoftDollarTiers.softDollarTiers)
  return softdollartiers_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::SoftDollarTier >*
SoftDollarTiers::mutable_softdollartiers() {
  // @@protoc_insertion_point(field_mutable_list:protobuf.SoftDollarTiers.softDollarTiers)
  return &softdollartiers_;
}
inline const ::protobuf::SoftDollarTier& SoftDollarTiers::_internal_softdollartiers(int index) const {
  return softdollartiers_.Get(index);
}
inline const ::protobuf::SoftDollarTier& SoftDollarTiers::softdollartiers(int index) const {
  // @@protoc_insertion_point(field_get:protobuf.SoftDollarTiers.softDollarTiers)
  return _internal_softdollartiers(index);
}
inline ::protobuf::SoftDollarTier* SoftDollarTiers::_internal_add_softdollartiers() {
  return softdollartiers_.Add();
}
inline ::protobuf::SoftDollarTier* SoftDollarTiers::add_softdollartiers() {
  // @@protoc_insertion_point(field_add:protobuf.SoftDollarTiers.softDollarTiers)
  return _internal_add_softdollartiers();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::SoftDollarTier >&
SoftDollarTiers::softdollartiers() const {
  // @@protoc_insertion_point(field_list:protobuf.SoftDollarTiers.softDollarTiers)
  return softdollartiers_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SoftDollarTiers_2eproto
