// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TickByTickRequest.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_TickByTickRequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_TickByTickRequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Contract.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_TickByTickRequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_TickByTickRequest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TickByTickRequest_2eproto;
namespace protobuf {
class TickByTickRequest;
class TickByTickRequestDefaultTypeInternal;
extern TickByTickRequestDefaultTypeInternal _TickByTickRequest_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::protobuf::TickByTickRequest* Arena::CreateMaybeMessage<::protobuf::TickByTickRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf {

// ===================================================================

class TickByTickRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.TickByTickRequest) */ {
 public:
  inline TickByTickRequest() : TickByTickRequest(nullptr) {};
  virtual ~TickByTickRequest();

  TickByTickRequest(const TickByTickRequest& from);
  TickByTickRequest(TickByTickRequest&& from) noexcept
    : TickByTickRequest() {
    *this = ::std::move(from);
  }

  inline TickByTickRequest& operator=(const TickByTickRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TickByTickRequest& operator=(TickByTickRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TickByTickRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TickByTickRequest* internal_default_instance() {
    return reinterpret_cast<const TickByTickRequest*>(
               &_TickByTickRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TickByTickRequest& a, TickByTickRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(TickByTickRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TickByTickRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TickByTickRequest* New() const final {
    return CreateMaybeMessage<TickByTickRequest>(nullptr);
  }

  TickByTickRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TickByTickRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TickByTickRequest& from);
  void MergeFrom(const TickByTickRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TickByTickRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.TickByTickRequest";
  }
  protected:
  explicit TickByTickRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_TickByTickRequest_2eproto);
    return ::descriptor_table_TickByTickRequest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTickTypeFieldNumber = 3,
    kContractFieldNumber = 2,
    kReqIdFieldNumber = 1,
    kNumberOfTicksFieldNumber = 4,
    kIgnoreSizeFieldNumber = 5,
  };
  // string tickType = 3;
  bool has_ticktype() const;
  private:
  bool _internal_has_ticktype() const;
  public:
  void clear_ticktype();
  const std::string& ticktype() const;
  void set_ticktype(const std::string& value);
  void set_ticktype(std::string&& value);
  void set_ticktype(const char* value);
  void set_ticktype(const char* value, size_t size);
  std::string* mutable_ticktype();
  std::string* release_ticktype();
  void set_allocated_ticktype(std::string* ticktype);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_ticktype();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_ticktype(
      std::string* ticktype);
  private:
  const std::string& _internal_ticktype() const;
  void _internal_set_ticktype(const std::string& value);
  std::string* _internal_mutable_ticktype();
  public:

  // .protobuf.Contract contract = 2;
  bool has_contract() const;
  private:
  bool _internal_has_contract() const;
  public:
  void clear_contract();
  const ::protobuf::Contract& contract() const;
  ::protobuf::Contract* release_contract();
  ::protobuf::Contract* mutable_contract();
  void set_allocated_contract(::protobuf::Contract* contract);
  private:
  const ::protobuf::Contract& _internal_contract() const;
  ::protobuf::Contract* _internal_mutable_contract();
  public:
  void unsafe_arena_set_allocated_contract(
      ::protobuf::Contract* contract);
  ::protobuf::Contract* unsafe_arena_release_contract();

  // int32 reqId = 1;
  bool has_reqid() const;
  private:
  bool _internal_has_reqid() const;
  public:
  void clear_reqid();
  ::PROTOBUF_NAMESPACE_ID::int32 reqid() const;
  void set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_reqid() const;
  void _internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 numberOfTicks = 4;
  bool has_numberofticks() const;
  private:
  bool _internal_has_numberofticks() const;
  public:
  void clear_numberofticks();
  ::PROTOBUF_NAMESPACE_ID::int32 numberofticks() const;
  void set_numberofticks(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_numberofticks() const;
  void _internal_set_numberofticks(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // bool ignoreSize = 5;
  bool has_ignoresize() const;
  private:
  bool _internal_has_ignoresize() const;
  public:
  void clear_ignoresize();
  bool ignoresize() const;
  void set_ignoresize(bool value);
  private:
  bool _internal_ignoresize() const;
  void _internal_set_ignoresize(bool value);
  public:

  // @@protoc_insertion_point(class_scope:protobuf.TickByTickRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ticktype_;
  ::protobuf::Contract* contract_;
  ::PROTOBUF_NAMESPACE_ID::int32 reqid_;
  ::PROTOBUF_NAMESPACE_ID::int32 numberofticks_;
  bool ignoresize_;
  friend struct ::TableStruct_TickByTickRequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TickByTickRequest

// int32 reqId = 1;
inline bool TickByTickRequest::_internal_has_reqid() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool TickByTickRequest::has_reqid() const {
  return _internal_has_reqid();
}
inline void TickByTickRequest::clear_reqid() {
  reqid_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TickByTickRequest::_internal_reqid() const {
  return reqid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TickByTickRequest::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.TickByTickRequest.reqId)
  return _internal_reqid();
}
inline void TickByTickRequest::_internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  reqid_ = value;
}
inline void TickByTickRequest::set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_reqid(value);
  // @@protoc_insertion_point(field_set:protobuf.TickByTickRequest.reqId)
}

// .protobuf.Contract contract = 2;
inline bool TickByTickRequest::_internal_has_contract() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || contract_ != nullptr);
  return value;
}
inline bool TickByTickRequest::has_contract() const {
  return _internal_has_contract();
}
inline const ::protobuf::Contract& TickByTickRequest::_internal_contract() const {
  const ::protobuf::Contract* p = contract_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protobuf::Contract*>(
      &::protobuf::_Contract_default_instance_);
}
inline const ::protobuf::Contract& TickByTickRequest::contract() const {
  // @@protoc_insertion_point(field_get:protobuf.TickByTickRequest.contract)
  return _internal_contract();
}
inline void TickByTickRequest::unsafe_arena_set_allocated_contract(
    ::protobuf::Contract* contract) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(contract_);
  }
  contract_ = contract;
  if (contract) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.TickByTickRequest.contract)
}
inline ::protobuf::Contract* TickByTickRequest::release_contract() {
  auto temp = unsafe_arena_release_contract();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::protobuf::Contract* TickByTickRequest::unsafe_arena_release_contract() {
  // @@protoc_insertion_point(field_release:protobuf.TickByTickRequest.contract)
  _has_bits_[0] &= ~0x00000002u;
  ::protobuf::Contract* temp = contract_;
  contract_ = nullptr;
  return temp;
}
inline ::protobuf::Contract* TickByTickRequest::_internal_mutable_contract() {
  _has_bits_[0] |= 0x00000002u;
  if (contract_ == nullptr) {
    auto* p = CreateMaybeMessage<::protobuf::Contract>(GetArena());
    contract_ = p;
  }
  return contract_;
}
inline ::protobuf::Contract* TickByTickRequest::mutable_contract() {
  // @@protoc_insertion_point(field_mutable:protobuf.TickByTickRequest.contract)
  return _internal_mutable_contract();
}
inline void TickByTickRequest::set_allocated_contract(::protobuf::Contract* contract) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(contract_);
  }
  if (contract) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(contract)->GetArena();
    if (message_arena != submessage_arena) {
      contract = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, contract, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  contract_ = contract;
  // @@protoc_insertion_point(field_set_allocated:protobuf.TickByTickRequest.contract)
}

// string tickType = 3;
inline bool TickByTickRequest::_internal_has_ticktype() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TickByTickRequest::has_ticktype() const {
  return _internal_has_ticktype();
}
inline void TickByTickRequest::clear_ticktype() {
  ticktype_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TickByTickRequest::ticktype() const {
  // @@protoc_insertion_point(field_get:protobuf.TickByTickRequest.tickType)
  return _internal_ticktype();
}
inline void TickByTickRequest::set_ticktype(const std::string& value) {
  _internal_set_ticktype(value);
  // @@protoc_insertion_point(field_set:protobuf.TickByTickRequest.tickType)
}
inline std::string* TickByTickRequest::mutable_ticktype() {
  // @@protoc_insertion_point(field_mutable:protobuf.TickByTickRequest.tickType)
  return _internal_mutable_ticktype();
}
inline const std::string& TickByTickRequest::_internal_ticktype() const {
  return ticktype_.Get();
}
inline void TickByTickRequest::_internal_set_ticktype(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  ticktype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TickByTickRequest::set_ticktype(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  ticktype_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:protobuf.TickByTickRequest.tickType)
}
inline void TickByTickRequest::set_ticktype(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  ticktype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:protobuf.TickByTickRequest.tickType)
}
inline void TickByTickRequest::set_ticktype(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  ticktype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:protobuf.TickByTickRequest.tickType)
}
inline std::string* TickByTickRequest::_internal_mutable_ticktype() {
  _has_bits_[0] |= 0x00000001u;
  return ticktype_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TickByTickRequest::release_ticktype() {
  // @@protoc_insertion_point(field_release:protobuf.TickByTickRequest.tickType)
  if (!_internal_has_ticktype()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return ticktype_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TickByTickRequest::set_allocated_ticktype(std::string* ticktype) {
  if (ticktype != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  ticktype_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ticktype,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:protobuf.TickByTickRequest.tickType)
}
inline std::string* TickByTickRequest::unsafe_arena_release_ticktype() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobuf.TickByTickRequest.tickType)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return ticktype_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TickByTickRequest::unsafe_arena_set_allocated_ticktype(
    std::string* ticktype) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (ticktype != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  ticktype_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ticktype, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.TickByTickRequest.tickType)
}

// int32 numberOfTicks = 4;
inline bool TickByTickRequest::_internal_has_numberofticks() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool TickByTickRequest::has_numberofticks() const {
  return _internal_has_numberofticks();
}
inline void TickByTickRequest::clear_numberofticks() {
  numberofticks_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TickByTickRequest::_internal_numberofticks() const {
  return numberofticks_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TickByTickRequest::numberofticks() const {
  // @@protoc_insertion_point(field_get:protobuf.TickByTickRequest.numberOfTicks)
  return _internal_numberofticks();
}
inline void TickByTickRequest::_internal_set_numberofticks(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  numberofticks_ = value;
}
inline void TickByTickRequest::set_numberofticks(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_numberofticks(value);
  // @@protoc_insertion_point(field_set:protobuf.TickByTickRequest.numberOfTicks)
}

// bool ignoreSize = 5;
inline bool TickByTickRequest::_internal_has_ignoresize() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool TickByTickRequest::has_ignoresize() const {
  return _internal_has_ignoresize();
}
inline void TickByTickRequest::clear_ignoresize() {
  ignoresize_ = false;
  _has_bits_[0] &= ~0x00000010u;
}
inline bool TickByTickRequest::_internal_ignoresize() const {
  return ignoresize_;
}
inline bool TickByTickRequest::ignoresize() const {
  // @@protoc_insertion_point(field_get:protobuf.TickByTickRequest.ignoreSize)
  return _internal_ignoresize();
}
inline void TickByTickRequest::_internal_set_ignoresize(bool value) {
  _has_bits_[0] |= 0x00000010u;
  ignoresize_ = value;
}
inline void TickByTickRequest::set_ignoresize(bool value) {
  _internal_set_ignoresize(value);
  // @@protoc_insertion_point(field_set:protobuf.TickByTickRequest.ignoreSize)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_TickByTickRequest_2eproto
