// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateConfigResponse.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_UpdateConfigResponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_UpdateConfigResponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "UpdateConfigWarning.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_UpdateConfigResponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_UpdateConfigResponse_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_UpdateConfigResponse_2eproto;
namespace protobuf {
class UpdateConfigResponse;
class UpdateConfigResponseDefaultTypeInternal;
extern UpdateConfigResponseDefaultTypeInternal _UpdateConfigResponse_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::protobuf::UpdateConfigResponse* Arena::CreateMaybeMessage<::protobuf::UpdateConfigResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf {

// ===================================================================

class UpdateConfigResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.UpdateConfigResponse) */ {
 public:
  inline UpdateConfigResponse() : UpdateConfigResponse(nullptr) {};
  virtual ~UpdateConfigResponse();

  UpdateConfigResponse(const UpdateConfigResponse& from);
  UpdateConfigResponse(UpdateConfigResponse&& from) noexcept
    : UpdateConfigResponse() {
    *this = ::std::move(from);
  }

  inline UpdateConfigResponse& operator=(const UpdateConfigResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateConfigResponse& operator=(UpdateConfigResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UpdateConfigResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateConfigResponse* internal_default_instance() {
    return reinterpret_cast<const UpdateConfigResponse*>(
               &_UpdateConfigResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UpdateConfigResponse& a, UpdateConfigResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateConfigResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateConfigResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UpdateConfigResponse* New() const final {
    return CreateMaybeMessage<UpdateConfigResponse>(nullptr);
  }

  UpdateConfigResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UpdateConfigResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UpdateConfigResponse& from);
  void MergeFrom(const UpdateConfigResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateConfigResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.UpdateConfigResponse";
  }
  protected:
  explicit UpdateConfigResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_UpdateConfigResponse_2eproto);
    return ::descriptor_table_UpdateConfigResponse_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChangedFieldsFieldNumber = 4,
    kErrorsFieldNumber = 5,
    kWarningsFieldNumber = 6,
    kStatusFieldNumber = 2,
    kMessageFieldNumber = 3,
    kReqIdFieldNumber = 1,
  };
  // repeated string changedFields = 4;
  int changedfields_size() const;
  private:
  int _internal_changedfields_size() const;
  public:
  void clear_changedfields();
  const std::string& changedfields(int index) const;
  std::string* mutable_changedfields(int index);
  void set_changedfields(int index, const std::string& value);
  void set_changedfields(int index, std::string&& value);
  void set_changedfields(int index, const char* value);
  void set_changedfields(int index, const char* value, size_t size);
  std::string* add_changedfields();
  void add_changedfields(const std::string& value);
  void add_changedfields(std::string&& value);
  void add_changedfields(const char* value);
  void add_changedfields(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& changedfields() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_changedfields();
  private:
  const std::string& _internal_changedfields(int index) const;
  std::string* _internal_add_changedfields();
  public:

  // repeated string errors = 5;
  int errors_size() const;
  private:
  int _internal_errors_size() const;
  public:
  void clear_errors();
  const std::string& errors(int index) const;
  std::string* mutable_errors(int index);
  void set_errors(int index, const std::string& value);
  void set_errors(int index, std::string&& value);
  void set_errors(int index, const char* value);
  void set_errors(int index, const char* value, size_t size);
  std::string* add_errors();
  void add_errors(const std::string& value);
  void add_errors(std::string&& value);
  void add_errors(const char* value);
  void add_errors(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& errors() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_errors();
  private:
  const std::string& _internal_errors(int index) const;
  std::string* _internal_add_errors();
  public:

  // repeated .protobuf.UpdateConfigWarning warnings = 6;
  int warnings_size() const;
  private:
  int _internal_warnings_size() const;
  public:
  void clear_warnings();
  ::protobuf::UpdateConfigWarning* mutable_warnings(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::UpdateConfigWarning >*
      mutable_warnings();
  private:
  const ::protobuf::UpdateConfigWarning& _internal_warnings(int index) const;
  ::protobuf::UpdateConfigWarning* _internal_add_warnings();
  public:
  const ::protobuf::UpdateConfigWarning& warnings(int index) const;
  ::protobuf::UpdateConfigWarning* add_warnings();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::UpdateConfigWarning >&
      warnings() const;

  // string status = 2;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  const std::string& status() const;
  void set_status(const std::string& value);
  void set_status(std::string&& value);
  void set_status(const char* value);
  void set_status(const char* value, size_t size);
  std::string* mutable_status();
  std::string* release_status();
  void set_allocated_status(std::string* status);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_status();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_status(
      std::string* status);
  private:
  const std::string& _internal_status() const;
  void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // string message = 3;
  bool has_message() const;
  private:
  bool _internal_has_message() const;
  public:
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // int32 reqId = 1;
  bool has_reqid() const;
  private:
  bool _internal_has_reqid() const;
  public:
  void clear_reqid();
  ::PROTOBUF_NAMESPACE_ID::int32 reqid() const;
  void set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_reqid() const;
  void _internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protobuf.UpdateConfigResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> changedfields_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> errors_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::UpdateConfigWarning > warnings_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::int32 reqid_;
  friend struct ::TableStruct_UpdateConfigResponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UpdateConfigResponse

// int32 reqId = 1;
inline bool UpdateConfigResponse::_internal_has_reqid() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool UpdateConfigResponse::has_reqid() const {
  return _internal_has_reqid();
}
inline void UpdateConfigResponse::clear_reqid() {
  reqid_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UpdateConfigResponse::_internal_reqid() const {
  return reqid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UpdateConfigResponse::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.UpdateConfigResponse.reqId)
  return _internal_reqid();
}
inline void UpdateConfigResponse::_internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  reqid_ = value;
}
inline void UpdateConfigResponse::set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_reqid(value);
  // @@protoc_insertion_point(field_set:protobuf.UpdateConfigResponse.reqId)
}

// string status = 2;
inline bool UpdateConfigResponse::_internal_has_status() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool UpdateConfigResponse::has_status() const {
  return _internal_has_status();
}
inline void UpdateConfigResponse::clear_status() {
  status_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& UpdateConfigResponse::status() const {
  // @@protoc_insertion_point(field_get:protobuf.UpdateConfigResponse.status)
  return _internal_status();
}
inline void UpdateConfigResponse::set_status(const std::string& value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:protobuf.UpdateConfigResponse.status)
}
inline std::string* UpdateConfigResponse::mutable_status() {
  // @@protoc_insertion_point(field_mutable:protobuf.UpdateConfigResponse.status)
  return _internal_mutable_status();
}
inline const std::string& UpdateConfigResponse::_internal_status() const {
  return status_.Get();
}
inline void UpdateConfigResponse::_internal_set_status(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  status_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UpdateConfigResponse::set_status(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  status_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:protobuf.UpdateConfigResponse.status)
}
inline void UpdateConfigResponse::set_status(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  status_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:protobuf.UpdateConfigResponse.status)
}
inline void UpdateConfigResponse::set_status(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  status_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:protobuf.UpdateConfigResponse.status)
}
inline std::string* UpdateConfigResponse::_internal_mutable_status() {
  _has_bits_[0] |= 0x00000001u;
  return status_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UpdateConfigResponse::release_status() {
  // @@protoc_insertion_point(field_release:protobuf.UpdateConfigResponse.status)
  if (!_internal_has_status()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return status_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UpdateConfigResponse::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  status_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), status,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:protobuf.UpdateConfigResponse.status)
}
inline std::string* UpdateConfigResponse::unsafe_arena_release_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobuf.UpdateConfigResponse.status)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return status_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void UpdateConfigResponse::unsafe_arena_set_allocated_status(
    std::string* status) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (status != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  status_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      status, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.UpdateConfigResponse.status)
}

// string message = 3;
inline bool UpdateConfigResponse::_internal_has_message() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool UpdateConfigResponse::has_message() const {
  return _internal_has_message();
}
inline void UpdateConfigResponse::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& UpdateConfigResponse::message() const {
  // @@protoc_insertion_point(field_get:protobuf.UpdateConfigResponse.message)
  return _internal_message();
}
inline void UpdateConfigResponse::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:protobuf.UpdateConfigResponse.message)
}
inline std::string* UpdateConfigResponse::mutable_message() {
  // @@protoc_insertion_point(field_mutable:protobuf.UpdateConfigResponse.message)
  return _internal_mutable_message();
}
inline const std::string& UpdateConfigResponse::_internal_message() const {
  return message_.Get();
}
inline void UpdateConfigResponse::_internal_set_message(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UpdateConfigResponse::set_message(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:protobuf.UpdateConfigResponse.message)
}
inline void UpdateConfigResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:protobuf.UpdateConfigResponse.message)
}
inline void UpdateConfigResponse::set_message(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:protobuf.UpdateConfigResponse.message)
}
inline std::string* UpdateConfigResponse::_internal_mutable_message() {
  _has_bits_[0] |= 0x00000002u;
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UpdateConfigResponse::release_message() {
  // @@protoc_insertion_point(field_release:protobuf.UpdateConfigResponse.message)
  if (!_internal_has_message()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return message_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UpdateConfigResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:protobuf.UpdateConfigResponse.message)
}
inline std::string* UpdateConfigResponse::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobuf.UpdateConfigResponse.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000002u;
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void UpdateConfigResponse::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.UpdateConfigResponse.message)
}

// repeated string changedFields = 4;
inline int UpdateConfigResponse::_internal_changedfields_size() const {
  return changedfields_.size();
}
inline int UpdateConfigResponse::changedfields_size() const {
  return _internal_changedfields_size();
}
inline void UpdateConfigResponse::clear_changedfields() {
  changedfields_.Clear();
}
inline std::string* UpdateConfigResponse::add_changedfields() {
  // @@protoc_insertion_point(field_add_mutable:protobuf.UpdateConfigResponse.changedFields)
  return _internal_add_changedfields();
}
inline const std::string& UpdateConfigResponse::_internal_changedfields(int index) const {
  return changedfields_.Get(index);
}
inline const std::string& UpdateConfigResponse::changedfields(int index) const {
  // @@protoc_insertion_point(field_get:protobuf.UpdateConfigResponse.changedFields)
  return _internal_changedfields(index);
}
inline std::string* UpdateConfigResponse::mutable_changedfields(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf.UpdateConfigResponse.changedFields)
  return changedfields_.Mutable(index);
}
inline void UpdateConfigResponse::set_changedfields(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:protobuf.UpdateConfigResponse.changedFields)
  changedfields_.Mutable(index)->assign(value);
}
inline void UpdateConfigResponse::set_changedfields(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:protobuf.UpdateConfigResponse.changedFields)
  changedfields_.Mutable(index)->assign(std::move(value));
}
inline void UpdateConfigResponse::set_changedfields(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  changedfields_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:protobuf.UpdateConfigResponse.changedFields)
}
inline void UpdateConfigResponse::set_changedfields(int index, const char* value, size_t size) {
  changedfields_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protobuf.UpdateConfigResponse.changedFields)
}
inline std::string* UpdateConfigResponse::_internal_add_changedfields() {
  return changedfields_.Add();
}
inline void UpdateConfigResponse::add_changedfields(const std::string& value) {
  changedfields_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:protobuf.UpdateConfigResponse.changedFields)
}
inline void UpdateConfigResponse::add_changedfields(std::string&& value) {
  changedfields_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:protobuf.UpdateConfigResponse.changedFields)
}
inline void UpdateConfigResponse::add_changedfields(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  changedfields_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:protobuf.UpdateConfigResponse.changedFields)
}
inline void UpdateConfigResponse::add_changedfields(const char* value, size_t size) {
  changedfields_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:protobuf.UpdateConfigResponse.changedFields)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
UpdateConfigResponse::changedfields() const {
  // @@protoc_insertion_point(field_list:protobuf.UpdateConfigResponse.changedFields)
  return changedfields_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
UpdateConfigResponse::mutable_changedfields() {
  // @@protoc_insertion_point(field_mutable_list:protobuf.UpdateConfigResponse.changedFields)
  return &changedfields_;
}

// repeated string errors = 5;
inline int UpdateConfigResponse::_internal_errors_size() const {
  return errors_.size();
}
inline int UpdateConfigResponse::errors_size() const {
  return _internal_errors_size();
}
inline void UpdateConfigResponse::clear_errors() {
  errors_.Clear();
}
inline std::string* UpdateConfigResponse::add_errors() {
  // @@protoc_insertion_point(field_add_mutable:protobuf.UpdateConfigResponse.errors)
  return _internal_add_errors();
}
inline const std::string& UpdateConfigResponse::_internal_errors(int index) const {
  return errors_.Get(index);
}
inline const std::string& UpdateConfigResponse::errors(int index) const {
  // @@protoc_insertion_point(field_get:protobuf.UpdateConfigResponse.errors)
  return _internal_errors(index);
}
inline std::string* UpdateConfigResponse::mutable_errors(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf.UpdateConfigResponse.errors)
  return errors_.Mutable(index);
}
inline void UpdateConfigResponse::set_errors(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:protobuf.UpdateConfigResponse.errors)
  errors_.Mutable(index)->assign(value);
}
inline void UpdateConfigResponse::set_errors(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:protobuf.UpdateConfigResponse.errors)
  errors_.Mutable(index)->assign(std::move(value));
}
inline void UpdateConfigResponse::set_errors(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  errors_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:protobuf.UpdateConfigResponse.errors)
}
inline void UpdateConfigResponse::set_errors(int index, const char* value, size_t size) {
  errors_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protobuf.UpdateConfigResponse.errors)
}
inline std::string* UpdateConfigResponse::_internal_add_errors() {
  return errors_.Add();
}
inline void UpdateConfigResponse::add_errors(const std::string& value) {
  errors_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:protobuf.UpdateConfigResponse.errors)
}
inline void UpdateConfigResponse::add_errors(std::string&& value) {
  errors_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:protobuf.UpdateConfigResponse.errors)
}
inline void UpdateConfigResponse::add_errors(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  errors_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:protobuf.UpdateConfigResponse.errors)
}
inline void UpdateConfigResponse::add_errors(const char* value, size_t size) {
  errors_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:protobuf.UpdateConfigResponse.errors)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
UpdateConfigResponse::errors() const {
  // @@protoc_insertion_point(field_list:protobuf.UpdateConfigResponse.errors)
  return errors_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
UpdateConfigResponse::mutable_errors() {
  // @@protoc_insertion_point(field_mutable_list:protobuf.UpdateConfigResponse.errors)
  return &errors_;
}

// repeated .protobuf.UpdateConfigWarning warnings = 6;
inline int UpdateConfigResponse::_internal_warnings_size() const {
  return warnings_.size();
}
inline int UpdateConfigResponse::warnings_size() const {
  return _internal_warnings_size();
}
inline ::protobuf::UpdateConfigWarning* UpdateConfigResponse::mutable_warnings(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf.UpdateConfigResponse.warnings)
  return warnings_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::UpdateConfigWarning >*
UpdateConfigResponse::mutable_warnings() {
  // @@protoc_insertion_point(field_mutable_list:protobuf.UpdateConfigResponse.warnings)
  return &warnings_;
}
inline const ::protobuf::UpdateConfigWarning& UpdateConfigResponse::_internal_warnings(int index) const {
  return warnings_.Get(index);
}
inline const ::protobuf::UpdateConfigWarning& UpdateConfigResponse::warnings(int index) const {
  // @@protoc_insertion_point(field_get:protobuf.UpdateConfigResponse.warnings)
  return _internal_warnings(index);
}
inline ::protobuf::UpdateConfigWarning* UpdateConfigResponse::_internal_add_warnings() {
  return warnings_.Add();
}
inline ::protobuf::UpdateConfigWarning* UpdateConfigResponse::add_warnings() {
  // @@protoc_insertion_point(field_add:protobuf.UpdateConfigResponse.warnings)
  return _internal_add_warnings();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::UpdateConfigWarning >&
UpdateConfigResponse::warnings() const {
  // @@protoc_insertion_point(field_list:protobuf.UpdateConfigResponse.warnings)
  return warnings_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_UpdateConfigResponse_2eproto
