// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VerifyCompleted.proto

#include "VerifyCompleted.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace protobuf {
class VerifyCompletedDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<VerifyCompleted> _instance;
} _VerifyCompleted_default_instance_;
}  // namespace protobuf
static void InitDefaultsscc_info_VerifyCompleted_VerifyCompleted_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protobuf::_VerifyCompleted_default_instance_;
    new (ptr) ::protobuf::VerifyCompleted();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protobuf::VerifyCompleted::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_VerifyCompleted_VerifyCompleted_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_VerifyCompleted_VerifyCompleted_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_VerifyCompleted_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_VerifyCompleted_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_VerifyCompleted_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_VerifyCompleted_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::protobuf::VerifyCompleted, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protobuf::VerifyCompleted, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protobuf::VerifyCompleted, issuccessful_),
  PROTOBUF_FIELD_OFFSET(::protobuf::VerifyCompleted, errortext_),
  1,
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::protobuf::VerifyCompleted)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_VerifyCompleted_default_instance_),
};

const char descriptor_table_protodef_VerifyCompleted_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025VerifyCompleted.proto\022\010protobuf\"c\n\017Ver"
  "ifyCompleted\022\031\n\014isSuccessful\030\001 \001(\010H\000\210\001\001\022"
  "\026\n\terrorText\030\002 \001(\tH\001\210\001\001B\017\n\r_isSuccessful"
  "B\014\n\n_errorTextB\?\n\026com.ib.client.protobuf"
  "B\024VerifyCompletedProto\252\002\016IBApi.protobufb"
  "\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_VerifyCompleted_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_VerifyCompleted_2eproto_sccs[1] = {
  &scc_info_VerifyCompleted_VerifyCompleted_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_VerifyCompleted_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_VerifyCompleted_2eproto = {
  false, false, descriptor_table_protodef_VerifyCompleted_2eproto, "VerifyCompleted.proto", 207,
  &descriptor_table_VerifyCompleted_2eproto_once, descriptor_table_VerifyCompleted_2eproto_sccs, descriptor_table_VerifyCompleted_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_VerifyCompleted_2eproto::offsets,
  file_level_metadata_VerifyCompleted_2eproto, 1, file_level_enum_descriptors_VerifyCompleted_2eproto, file_level_service_descriptors_VerifyCompleted_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_VerifyCompleted_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_VerifyCompleted_2eproto)), true);
namespace protobuf {

// ===================================================================

void VerifyCompleted::InitAsDefaultInstance() {
}
class VerifyCompleted::_Internal {
 public:
  using HasBits = decltype(std::declval<VerifyCompleted>()._has_bits_);
  static void set_has_issuccessful(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_errortext(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

VerifyCompleted::VerifyCompleted(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.VerifyCompleted)
}
VerifyCompleted::VerifyCompleted(const VerifyCompleted& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  errortext_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_errortext()) {
    errortext_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_errortext(),
      GetArena());
  }
  issuccessful_ = from.issuccessful_;
  // @@protoc_insertion_point(copy_constructor:protobuf.VerifyCompleted)
}

void VerifyCompleted::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_VerifyCompleted_VerifyCompleted_2eproto.base);
  errortext_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  issuccessful_ = false;
}

VerifyCompleted::~VerifyCompleted() {
  // @@protoc_insertion_point(destructor:protobuf.VerifyCompleted)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void VerifyCompleted::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  errortext_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void VerifyCompleted::ArenaDtor(void* object) {
  VerifyCompleted* _this = reinterpret_cast< VerifyCompleted* >(object);
  (void)_this;
}
void VerifyCompleted::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void VerifyCompleted::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const VerifyCompleted& VerifyCompleted::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_VerifyCompleted_VerifyCompleted_2eproto.base);
  return *internal_default_instance();
}


void VerifyCompleted::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.VerifyCompleted)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    errortext_.ClearNonDefaultToEmpty();
  }
  issuccessful_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VerifyCompleted::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool isSuccessful = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_issuccessful(&has_bits);
          issuccessful_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string errorText = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_errortext();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.VerifyCompleted.errorText"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* VerifyCompleted::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.VerifyCompleted)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool isSuccessful = 1;
  if (_internal_has_issuccessful()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_issuccessful(), target);
  }

  // string errorText = 2;
  if (_internal_has_errortext()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_errortext().data(), static_cast<int>(this->_internal_errortext().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.VerifyCompleted.errorText");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_errortext(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.VerifyCompleted)
  return target;
}

size_t VerifyCompleted::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.VerifyCompleted)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // string errorText = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_errortext());
    }

    // bool isSuccessful = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VerifyCompleted::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protobuf.VerifyCompleted)
  GOOGLE_DCHECK_NE(&from, this);
  const VerifyCompleted* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<VerifyCompleted>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protobuf.VerifyCompleted)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protobuf.VerifyCompleted)
    MergeFrom(*source);
  }
}

void VerifyCompleted::MergeFrom(const VerifyCompleted& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.VerifyCompleted)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_errortext(from._internal_errortext());
    }
    if (cached_has_bits & 0x00000002u) {
      issuccessful_ = from.issuccessful_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void VerifyCompleted::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protobuf.VerifyCompleted)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VerifyCompleted::CopyFrom(const VerifyCompleted& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.VerifyCompleted)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VerifyCompleted::IsInitialized() const {
  return true;
}

void VerifyCompleted::InternalSwap(VerifyCompleted* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  errortext_.Swap(&other->errortext_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(issuccessful_, other->issuccessful_);
}

::PROTOBUF_NAMESPACE_ID::Metadata VerifyCompleted::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::VerifyCompleted* Arena::CreateMaybeMessage< ::protobuf::VerifyCompleted >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::VerifyCompleted >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
