// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WshEventDataRequest.proto

#include "WshEventDataRequest.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace protobuf {
class WshEventDataRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<WshEventDataRequest> _instance;
} _WshEventDataRequest_default_instance_;
}  // namespace protobuf
static void InitDefaultsscc_info_WshEventDataRequest_WshEventDataRequest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protobuf::_WshEventDataRequest_default_instance_;
    new (ptr) ::protobuf::WshEventDataRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protobuf::WshEventDataRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_WshEventDataRequest_WshEventDataRequest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_WshEventDataRequest_WshEventDataRequest_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_WshEventDataRequest_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_WshEventDataRequest_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_WshEventDataRequest_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_WshEventDataRequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, reqid_),
  PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, conid_),
  PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, filter_),
  PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, fillwatchlist_),
  PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, fillportfolio_),
  PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, fillcompetitors_),
  PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, startdate_),
  PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, enddate_),
  PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, totallimit_),
  3,
  4,
  0,
  5,
  6,
  7,
  1,
  2,
  8,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 14, sizeof(::protobuf::WshEventDataRequest)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protobuf::_WshEventDataRequest_default_instance_),
};

const char descriptor_table_protodef_WshEventDataRequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031WshEventDataRequest.proto\022\010protobuf\"\357\002"
  "\n\023WshEventDataRequest\022\022\n\005reqId\030\001 \001(\005H\000\210\001"
  "\001\022\022\n\005conId\030\002 \001(\005H\001\210\001\001\022\023\n\006filter\030\003 \001(\tH\002\210"
  "\001\001\022\032\n\rfillWatchlist\030\004 \001(\010H\003\210\001\001\022\032\n\rfillPo"
  "rtfolio\030\005 \001(\010H\004\210\001\001\022\034\n\017fillCompetitors\030\006 "
  "\001(\010H\005\210\001\001\022\026\n\tstartDate\030\007 \001(\tH\006\210\001\001\022\024\n\007endD"
  "ate\030\010 \001(\tH\007\210\001\001\022\027\n\ntotalLimit\030\t \001(\005H\010\210\001\001B"
  "\010\n\006_reqIdB\010\n\006_conIdB\t\n\007_filterB\020\n\016_fillW"
  "atchlistB\020\n\016_fillPortfolioB\022\n\020_fillCompe"
  "titorsB\014\n\n_startDateB\n\n\010_endDateB\r\n\013_tot"
  "alLimitBC\n\026com.ib.client.protobufB\030WshEv"
  "entDataRequestProto\252\002\016IBApi.protobufb\006pr"
  "oto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_WshEventDataRequest_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_WshEventDataRequest_2eproto_sccs[1] = {
  &scc_info_WshEventDataRequest_WshEventDataRequest_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_WshEventDataRequest_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_WshEventDataRequest_2eproto = {
  false, false, descriptor_table_protodef_WshEventDataRequest_2eproto, "WshEventDataRequest.proto", 484,
  &descriptor_table_WshEventDataRequest_2eproto_once, descriptor_table_WshEventDataRequest_2eproto_sccs, descriptor_table_WshEventDataRequest_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_WshEventDataRequest_2eproto::offsets,
  file_level_metadata_WshEventDataRequest_2eproto, 1, file_level_enum_descriptors_WshEventDataRequest_2eproto, file_level_service_descriptors_WshEventDataRequest_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_WshEventDataRequest_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_WshEventDataRequest_2eproto)), true);
namespace protobuf {

// ===================================================================

void WshEventDataRequest::InitAsDefaultInstance() {
}
class WshEventDataRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<WshEventDataRequest>()._has_bits_);
  static void set_has_reqid(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_conid(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_filter(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_fillwatchlist(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_fillportfolio(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_fillcompetitors(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_startdate(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_enddate(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_totallimit(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
};

WshEventDataRequest::WshEventDataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.WshEventDataRequest)
}
WshEventDataRequest::WshEventDataRequest(const WshEventDataRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  filter_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_filter()) {
    filter_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_filter(),
      GetArena());
  }
  startdate_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_startdate()) {
    startdate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_startdate(),
      GetArena());
  }
  enddate_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_enddate()) {
    enddate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_enddate(),
      GetArena());
  }
  ::memcpy(&reqid_, &from.reqid_,
    static_cast<size_t>(reinterpret_cast<char*>(&totallimit_) -
    reinterpret_cast<char*>(&reqid_)) + sizeof(totallimit_));
  // @@protoc_insertion_point(copy_constructor:protobuf.WshEventDataRequest)
}

void WshEventDataRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_WshEventDataRequest_WshEventDataRequest_2eproto.base);
  filter_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  startdate_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  enddate_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&reqid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&totallimit_) -
      reinterpret_cast<char*>(&reqid_)) + sizeof(totallimit_));
}

WshEventDataRequest::~WshEventDataRequest() {
  // @@protoc_insertion_point(destructor:protobuf.WshEventDataRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void WshEventDataRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  filter_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  startdate_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  enddate_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void WshEventDataRequest::ArenaDtor(void* object) {
  WshEventDataRequest* _this = reinterpret_cast< WshEventDataRequest* >(object);
  (void)_this;
}
void WshEventDataRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void WshEventDataRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WshEventDataRequest& WshEventDataRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_WshEventDataRequest_WshEventDataRequest_2eproto.base);
  return *internal_default_instance();
}


void WshEventDataRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.WshEventDataRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      filter_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      startdate_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      enddate_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x000000f8u) {
    ::memset(&reqid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&fillcompetitors_) -
        reinterpret_cast<char*>(&reqid_)) + sizeof(fillcompetitors_));
  }
  totallimit_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WshEventDataRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 reqId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_reqid(&has_bits);
          reqid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 conId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_conid(&has_bits);
          conid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string filter = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_filter();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.WshEventDataRequest.filter"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool fillWatchlist = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          _Internal::set_has_fillwatchlist(&has_bits);
          fillwatchlist_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool fillPortfolio = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_fillportfolio(&has_bits);
          fillportfolio_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool fillCompetitors = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          _Internal::set_has_fillcompetitors(&has_bits);
          fillcompetitors_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string startDate = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          auto str = _internal_mutable_startdate();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.WshEventDataRequest.startDate"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string endDate = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          auto str = _internal_mutable_enddate();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protobuf.WshEventDataRequest.endDate"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 totalLimit = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          _Internal::set_has_totallimit(&has_bits);
          totallimit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* WshEventDataRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.WshEventDataRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 reqId = 1;
  if (_internal_has_reqid()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_reqid(), target);
  }

  // int32 conId = 2;
  if (_internal_has_conid()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_conid(), target);
  }

  // string filter = 3;
  if (_internal_has_filter()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filter().data(), static_cast<int>(this->_internal_filter().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.WshEventDataRequest.filter");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_filter(), target);
  }

  // bool fillWatchlist = 4;
  if (_internal_has_fillwatchlist()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_fillwatchlist(), target);
  }

  // bool fillPortfolio = 5;
  if (_internal_has_fillportfolio()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(5, this->_internal_fillportfolio(), target);
  }

  // bool fillCompetitors = 6;
  if (_internal_has_fillcompetitors()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(6, this->_internal_fillcompetitors(), target);
  }

  // string startDate = 7;
  if (_internal_has_startdate()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_startdate().data(), static_cast<int>(this->_internal_startdate().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.WshEventDataRequest.startDate");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_startdate(), target);
  }

  // string endDate = 8;
  if (_internal_has_enddate()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_enddate().data(), static_cast<int>(this->_internal_enddate().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.WshEventDataRequest.endDate");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_enddate(), target);
  }

  // int32 totalLimit = 9;
  if (_internal_has_totallimit()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(9, this->_internal_totallimit(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.WshEventDataRequest)
  return target;
}

size_t WshEventDataRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.WshEventDataRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // string filter = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_filter());
    }

    // string startDate = 7;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_startdate());
    }

    // string endDate = 8;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_enddate());
    }

    // int32 reqId = 1;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_reqid());
    }

    // int32 conId = 2;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_conid());
    }

    // bool fillWatchlist = 4;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 1;
    }

    // bool fillPortfolio = 5;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + 1;
    }

    // bool fillCompetitors = 6;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 + 1;
    }

  }
  // int32 totalLimit = 9;
  if (cached_has_bits & 0x00000100u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_totallimit());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WshEventDataRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protobuf.WshEventDataRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const WshEventDataRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<WshEventDataRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protobuf.WshEventDataRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protobuf.WshEventDataRequest)
    MergeFrom(*source);
  }
}

void WshEventDataRequest::MergeFrom(const WshEventDataRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protobuf.WshEventDataRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_filter(from._internal_filter());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_startdate(from._internal_startdate());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_set_enddate(from._internal_enddate());
    }
    if (cached_has_bits & 0x00000008u) {
      reqid_ = from.reqid_;
    }
    if (cached_has_bits & 0x00000010u) {
      conid_ = from.conid_;
    }
    if (cached_has_bits & 0x00000020u) {
      fillwatchlist_ = from.fillwatchlist_;
    }
    if (cached_has_bits & 0x00000040u) {
      fillportfolio_ = from.fillportfolio_;
    }
    if (cached_has_bits & 0x00000080u) {
      fillcompetitors_ = from.fillcompetitors_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00000100u) {
    _internal_set_totallimit(from._internal_totallimit());
  }
}

void WshEventDataRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protobuf.WshEventDataRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WshEventDataRequest::CopyFrom(const WshEventDataRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.WshEventDataRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WshEventDataRequest::IsInitialized() const {
  return true;
}

void WshEventDataRequest::InternalSwap(WshEventDataRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  filter_.Swap(&other->filter_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  startdate_.Swap(&other->startdate_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  enddate_.Swap(&other->enddate_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WshEventDataRequest, totallimit_)
      + sizeof(WshEventDataRequest::totallimit_)
      - PROTOBUF_FIELD_OFFSET(WshEventDataRequest, reqid_)>(
          reinterpret_cast<char*>(&reqid_),
          reinterpret_cast<char*>(&other->reqid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata WshEventDataRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::WshEventDataRequest* Arena::CreateMaybeMessage< ::protobuf::WshEventDataRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::WshEventDataRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
